force-app/main/default/objects/Account/fields/Centre_profit_partenaire__c.field-meta.xml
<CustomField>
    <fullName>Centre_profit_partenaire__c</fullName>
    <externalId>true</externalId>
    <label>Centre profit partenaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerCompany_Code__c.field-meta.xml
<CustomField>
    <fullName>PartnerCompany_Code__c</fullName>
    <label>Code société partenaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cost_center__mdt/Cost_center__mdt.object-meta.xml
<CustomObject>
    <label>Cost center</label>
    <pluralLabel>Cost centers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cost_center__mdt/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cost_center__mdt/fields/Cost_center__c.field-meta.xml
<CustomField>
    <fullName>Cost_center__c</fullName>
    <label>Cost center</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InfinityExportNumber__c/InfinityExportNumber__c.object-meta.xml
<CustomObject>
    <label>InfinityExportNumber</label>
    <nameField>
        <label>Nom de InfinityExportNumber</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InfinityExportNumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InfinityExportNumber__c/fields/Counter__c.field-meta.xml
<CustomField>
    <fullName>Counter__c</fullName>
    <label>Counter</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InfinityExportNumber__c/fields/LineCounter__c.field-meta.xml
<CustomField>
    <fullName>LineCounter__c</fullName>
    <label>LineCounter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCAPTIF&quot;), &quot;Non Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBRP&quot;), &quot;Régie Physique&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBHORSCAPTIF&quot;), &quot;Hors Captif&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBALIMENTAIR&quot;), &quot;Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPART&quot;), &quot;Cashback Webloyalty&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPROG&quot;), &quot;AdEx&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBNIP&quot;), &quot;NIP&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBAUTRES&quot;), &quot;Autres&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCLAB&quot;), &quot;CLAB&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBW2S&quot;), &quot;WEB TO STORE&quot;,
&quot;&quot;

))))))))))</formula>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Payeur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>AccountInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Avoir__c.field-meta.xml
<CustomField>
    <fullName>Avoir__c</fullName>
    <formula>NOT(ISBLANK( OriginalInvoiceNumber__c ))</formula>
    <label>Avoir ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BUs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Date Facture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <externalId>true</externalId>
    <label>N° Facture</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTerm__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTerm__c</fullName>
    <label>Date d&apos;échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OI_Number__c.field-meta.xml
<CustomField>
    <fullName>OI_Number__c</fullName>
    <formula>Opportunity__r.AutoOppId__c</formula>
    <label>Numéro d&apos;opportunité</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SentInvoice__c.field-meta.xml
<CustomField>
    <fullName>SentInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatiquement coché quand envoyé en facture</inlineHelpText>
    <label>Envoyé en facture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalExcludingVat__c.field-meta.xml
<CustomField>
    <fullName>TotalExcludingVat__c</fullName>
    <label>Total HT</label>
    <summarizedField>InvoiceItem__c.TotalExcludingVat__c</summarizedField>
    <summaryForeignKey>InvoiceItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalWithVat__c.field-meta.xml
<CustomField>
    <fullName>TotalWithVat__c</fullName>
    <formula>(TotalExcludingVat__c *  VatRate__c) + TotalExcludingVat__c</formula>
    <label>Total TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <formula>TotalWithVat__c -  TotalExcludingVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VatRate__c.field-meta.xml
<CustomField>
    <fullName>VatRate__c</fullName>
    <label>Taux de TVA</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Invoice_Export_Settings__mdt/Invoice_Export_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Invoice Export Settings</label>
    <pluralLabel>Invoice Export Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Invoice_Export_Settings__mdt/fields/error_recipients__c.field-meta.xml
<CustomField>
    <fullName>error_recipients__c</fullName>
    <label>error_recipients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Export_Settings__mdt/fields/info_recipients__c.field-meta.xml
<CustomField>
    <fullName>info_recipients__c</fullName>
    <label>info_recipients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Ligne de facture</label>
    <nameField>
        <label>Nom de la ligne de facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Insertion__c.field-meta.xml
<CustomField>
    <fullName>Insertion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insertion</label>
    <referenceTo>Insertion__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>invoiceitems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Ordre_interne__c.field-meta.xml
<CustomField>
    <fullName>Ordre_interne__c</fullName>
    <formula>text(Insertion__r.OpportunityProduct__r.Package__r.OrdreInterne__c)</formula>
    <label>Ordre interne</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/TotalExcludingVat__c.field-meta.xml
<CustomField>
    <fullName>TotalExcludingVat__c</fullName>
    <label>Total HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <formula>TotalExcludingVat__c *  Invoice__r.VatRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceNumber__c/InvoiceNumber__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>InvoiceNumber</label>
</CustomObject>

force-app/main/default/objects/InvoiceNumber__c/fields/counter__c.field-meta.xml
<CustomField>
    <fullName>counter__c</fullName>
    <label>counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/invoice_export.cls
public class invoice_export {
    public static List<ContentVersion> generatedFiles {
        get{
            if (generatedFiles == null) generatedFiles = new List<ContentVersion>();
            return generatedFiles;
        }
        set;
    }
    public static List<String> notGeneratedInvoices {
        get{
            if (notGeneratedInvoices == null) notGeneratedInvoices = new List<String>();
            return notGeneratedInvoices;
        }
        set;
    }
    public static Set<String> generatedInvoices {
        get{
            if (generatedInvoices == null) generatedInvoices = new Set<String>();
            return generatedInvoices;
        }
        set;
    }
    public static InfinityExportNumber__c infinityExportNumber{
        get{
            if (infinityExportNumber == null)
            infinityExportNumber = new InfinityExportNumber__c(Counter__c = 0);
            return infinityExportNumber;
        }
        
        set;
    }

    public static List<String> invoiceErrors{
        get{
            if (invoiceErrors == null) invoiceErrors = new List<String>();
            return invoiceErrors;
        }
        set;
    }
    
    //Define Json structure
    class fieldConf {
        String name;
        Integer length;
        String value;
    }
    class lineConf {
        List<fieldConf> line1;
        List<fieldConf> line2;
        List<fieldConf> line3;
        List<fieldConf> line4;
    }
    
    public static List<Invoice__c> invoices;
    public static Map<String, String> costCenter;
    public static lineConf facInfinity;

    // Invoice_Export_Settings__mdt contains report and error mail adresses.
    public static Invoice_Export_Settings__mdt export_settings = [SELECT DeveloperName, info_recipients__c, error_recipients__c FROM Invoice_Export_Settings__mdt WHERE DeveloperName = 'Mail_Export_Recipients' limit 1];
    
    static {
        Blob infinityExportJson = [select body from StaticResource Where Name = 'model_infinity_export'].Body; 
        facInfinity = (lineConf)JSON.deserialize(infinityExportJson.toString(), lineConf.class);
        
        //cost_center
        List<cost_center__mdt> ccs = [SELECT BU__c, cost_center__c FROM cost_center__mdt];
        costCenter = new Map<String, String> ();
        for( cost_center__mdt cc : ccs) costCenter.put(cc.BU__c, cc.cost_center__c);
        costCenter.put(null, 'NO_BU');
    }
    
    public invoice_export(ApexPages.StandardSetController controller) {
        invoices = [SELECT Id, Name, TotalWithVat__c, VAT_Amount__c, InvoiceTerm__c, InvoiceDate__c, InvoiceNumber__c, Avoir__c, OI_Number__c, BU__c, Account__r.Centre_profit_partenaire__c, Account__r.PartnerCompany_Code__c, VatRate__c, TotalExcludingVat__c,
                    (select id, Insertion__c, TotalExcludingVat__c, VAT_Amount__c, Ordre_Interne__c from InvoiceItems__r)
                    FROM Invoice__c
                    WHERE Id IN :controller.getSelected()];
        List<InfinityExportNumber__c> ltin = [SELECT Id, Counter__c, LineCounter__c FROM InfinityExportNumber__c ORDER BY Counter__c DESC LIMIT 1];
        if (ltin.size() > 0) infinityExportNumber = ltin[0];
        else{
            infinityExportNumber = new infinityExportNumber__c(Counter__c = 0, LineCounter__c = 0);
        }
    }
    
    public static void exportInfinity() {
        Map<String, String> infDataMap = new Map<String, String>();
        for(Invoice__c i : invoices) {
            generatedInvoices.add(i.Name);
        }
        infDataMap.put('infinity', writeInfinityInvoice(invoices));
        
        if(generatedInvoices.size() > 0) {
            Document docFactures = new Document(body = Blob.valueOf(String.join(infDataMap.values(),'\r\n')),
                                                folderid = UserInfo.getUserId(),
                                                name = 'winLogic_InfinityAds_'+System.now().format('yyyyMMddHHmmssSSS')+'.tgt');
            insert docFactures;
            
            ContentVersion fichierFactures = new ContentVersion();
            fichierFactures.ContentLocation = 'S';
            fichierFactures.VersionData = docFactures.Body;
            fichierFactures.Title = docFactures.Name;
            fichierFactures.PathOnClient = docFactures.Name;
            insert fichierFactures;
            system.debug(docFactures.Id);
            generatedFiles.add(fichierFactures);
            Set<Id> docSet = new Set<Id>();
            docSet.add(docFactures.Id);
            exportToMail(docSet);
        }
    }
    
    public static Document exportInfinitySched(List<Invoice__c> invoices) {
        Map<String, String> infDataMap = new Map<String, String>();
        infDataMap.put('infinity', writeInfinityInvoice(invoices));
        Document docFactures = new Document(body = Blob.valueOf(String.join(infDataMap.values(),'\r\n')),
                                            folderid = UserInfo.getUserId(),
                                            name = 'winLogic_InfinityAds_'+System.now().format('yyyyMMddHHmmssSSS')+'.tgt');
        return docFactures;
    }
    
    
    public static String writeInfinityInvoice(List<Invoice__c> invoiceList) {
        List<InfinityExportNumber__c> ltin = [SELECT Id, Counter__c, LineCounter__c FROM InfinityExportNumber__c ORDER BY Counter__c DESC LIMIT 1];
        if (ltin.size() > 0) infinityExportNumber = ltin[0];
        else{
            infinityExportNumber = new infinityExportNumber__c(Counter__c = 0, LineCounter__c = 0);
        }
        String output ='';
        Date lastMonthDate = Date.today().addMonths(-1);
        infinityExportNumber.counter__c++;
        Set<Id> invItemIds = new Set<Id>();
        
        for(Invoice__c inv : invoiceList){
            infinityExportNumber.lineCounter__c++;
            //START - line 1 Invoice
            for(fieldConf f : facInfinity.line1) { 
                if(f.value == 'blank'){
                    output += genValue('', f.length);
                }else if(f.value != ''){
                    if(f.value == 'E') output += genValue('E ', f.length);
                    else output += genValue(f.value, f.length);
                }else{
                    switch on f.name {
                        when 'societe' { // Si compta multi sociétés sinon 00000
                            output += genValue('00000', f.length);
                        }
                        when 'dateOrigPiece' {
                            Datetime dt = Date.Today();
                            if(inv.InvoiceDate__c != null) dt = inv.InvoiceDate__c;
                            output += genValue(dt.format('yyyyMMdd'), f.length);
                        }
                        when 'dateCompta' {
                            Datetime dt = Date.Today();
                            output += genValue(dt.format('yyyyMMdd'), f.length);
                        }
                        when 'dateEcheance' {
                            if(1==1){
                                Datetime dt = Date.Today();
                                if(inv.InvoiceTerm__c != null) dt = inv.InvoiceTerm__c;
                                output += genValue(dt.format('yyyyMMdd'), f.length);
                            }else{
                                output += genValue('', f.length);
                            }
                        }
                        when 'numPiece' {
                            output += genValue(inv.InvoiceNumber__c, f.length);
                        }
                        when 'descEcriture' {
                            output += genValue('Facture '+inv.OI_Number__c, f.length);
                        }
                        when 'signMontantEcriture' {
                            String signe = inv.Avoir__c ? '-' : '+';
                            output += genValue(signe, f.length);
                        }
                        when 'montantEcriture' {
                            output += genValue(inv.TotalExcludingVat__c , f.length);
                        }
                        when 'signeMontantTva' {
                            String signe = inv.Avoir__c ? '-' : '+';
                            output += genValue(signe, f.length);
                        }
                        when 'montantTva' {
                            output += genValue(inv.VAT_Amount__c , f.length);
                        }
                        when 'sensEcriture' {
                            String signe = inv.Avoir__c ? 'D' : 'C';
                            output += genValue(signe, f.length);
                        }
                        when 'codeDevise' {
                            output += genValue('EUR', f.length);
                        }
                        when 'ModeReglement' {
                            output += genValue(getModeReglement('00'), f.length);
                        }
                        when 'journal' { //(ne pas renseigner sur les lignes analytiques)
                            output += genValue('VE', f.length);
                        }
                        when 'compteGeneral' {
                            output += genValue('', f.length);
                        }
                        when 'compteAux' {
                            output += genValue('', f.length);
                        }
                        when 'sectAnaly1' {
                            output += genValue('', f.length);
                        }
                        when 'sectAnaly2' {
                            output += genValue('', f.length);
                        }
                        when 'sectAnaly3' {
                            output += genValue('', f.length);
                        }
                        when 'codeOrigPiece' {
                            output += genValue('', f.length);
                        }
                        when 'numOrig' {
                            output += genValue(String.valueOf(infinityExportNumber.LineCounter__c), f.length);
                        }
                        when 'finEnreg' {
                            output += genValue(';', f.length);
                        }
                        when else {
                            throw new infinityExportException('Error: Name not recognized at line 1 -> ' + f.name);
                        }
                    }
                }
            }
            output += '\r\n';
            //END - line 1 Invoice

            for(InvoiceItem__c invItem : inv.InvoiceItems__r){
                //START - line 1 InvoiceItem
                for(fieldConf f : facInfinity.line1) { 
                    if(f.value == 'blank'){
                        output += genValue('', f.length);
                    }else if(f.value != ''){
                        if(f.value == 'E') output += genValue('E ', f.length);
                        else output += genValue(f.value, f.length);
                    }else{
                        switch on f.name {
                            when 'societe' { // Si compta multi sociétés sinon 00000
                                output += genValue('00000', f.length);
                            }
                            when 'dateOrigPiece' {
                                Datetime dt = Date.Today();
                                if(inv.InvoiceDate__c != null) dt = inv.InvoiceDate__c;
                                output += genValue(dt.format('yyyyMMdd'), f.length);
                            }
                            when 'dateCompta' {
                                Datetime dt = Date.Today();
                                output += genValue(dt.format('yyyyMMdd'), f.length);
                            }
                            when 'dateEcheance' {
                                if(1==1){
                                    Datetime dt = Date.Today();
                                    if(inv.InvoiceTerm__c != null) dt = inv.InvoiceTerm__c;
                                    output += genValue(dt.format('yyyyMMdd'), f.length);
                                }else{
                                    output += genValue('', f.length);
                                }
                            }
                            when 'numPiece' {
                                output += genValue(inv.InvoiceNumber__c, f.length);
                            }
                            when 'descEcriture' {
                                output += genValue('Facture '+inv.OI_Number__c, f.length);
                            }
                            when 'signMontantEcriture' {
                                String signe = inv.Avoir__c ? '-' : '+';
                                output += genValue(signe, f.length);
                            }
                            when 'montantEcriture' {
                                output += genValue(invItem.TotalExcludingVat__c, f.length);
                            }
                            when 'signeMontantTva' {
                                String signe = inv.Avoir__c ? '-' : '+';
                                output += genValue(signe, f.length);
                            }
                            when 'montantTva' {
                                output += genValue(invItem.VAT_Amount__c, f.length);
                            }
                            when 'sensEcriture' {
                                String signe = inv.Avoir__c ? 'D' : 'C';
                                output += genValue(signe, f.length);
                            }
                            when 'codeDevise' {
                                output += genValue('EUR', f.length);
                            }
                            when 'ModeReglement' {
                                output += genValue(getModeReglement('00'), f.length);
                            }
                            when 'journal' { //(ne pas renseigner sur les lignes analytiques)
                                output += genValue('', f.length);
                            }
                            when 'compteGeneral' {
                                output += genValue('', f.length);
                            }
                            when 'compteAux' {
                                output += genValue('', f.length);
                            }
                            when 'sectAnaly1' {
                                output += genValue('', f.length);
                            }
                            when 'sectAnaly2' {
                                output += genValue('', f.length);
                            }
                            when 'sectAnaly3' {
                                output += genValue('', f.length);
                            }
                            when 'codeOrigPiece' {
                                output += genValue('', f.length);
                            }
                            when 'numOrig' {
                                output += genValue(String.valueOf(infinityExportNumber.LineCounter__c), f.length);
                            }
                            when 'finEnreg' {
                                output += genValue(';', f.length);
                            }
                            when else {
                                throw new infinityExportException('Error: Name not recognized at line 1 -> ' + f.name);
                            }
                        }
                    }
                }
                output += '\r\n';
            }
            //END - line 1 InvoiceItem
            inv.SentInvoice__c = true;
        }
        output += '\r\n';
        update infinityExportNumber;
        update invoiceList;
        system.debug(output);
        return output;
    }
    
    public class infinityExportException extends Exception{}

    @future(callout = true)
    public static void exportToMail(Set<Id> docSet){
        Id emailTemplateId = [SELECT Id, DeveloperName FROM EmailTemplate WHERE DeveloperName = 'ExportedInvoices' LIMIT 1].Id;
        List<Document> listDoc = [SELECT Id, Name, Body, Bodylength FROM Document WHERE Id IN: docSet];
        List<Id> docIdList = new List<Id>();
        for(Id docId : docSet){
            docIdList.add(docId);
        }
        String exportedFiles ='';
        if(listDoc.size() > 0){
            exportedFiles+= '\r\n';
        }else{
            system.debug(docSet);
            system.debug('no files');
            return;
        } 
        Messaging.SingleEmailMessage[] mailList = new List<Messaging.SingleEmailMessage>{};
        for(Document file : listDoc){
            exportedFiles += file.Name+'\r\n';
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String [] emailArray = Test.isRunningTest() ? new List<String>{'project@isochronix.com'} : export_settings.info_recipients__c.split(';');
            system.debug(emailArray);
            mail.toAddresses = emailArray;
            mail.setTemplateId(emailTemplateId);
            mail.setEntityAttachments(docIdList);
            mail.setTreatTargetObjectAsRecipient(false);
            mail.setTargetObjectId(UserInfo.getUserId());
            mailList.add(mail);
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(mailList);
    }
    
    private static String genValue(String value, Integer validLength){
        if(value == null) value = '';
        if(value.length() > validLength) value = value.substring(0, validLength);
        else value = value.rightPad(validLength, ' ');
        return removeAccents(value);
    }

    private static String genValue(Decimal value, Integer validLength){
        String returnValue;
        if(value == null) value = 0;
        if(String.valueOf(value).remove('.').length() > validLength) returnValue = String.valueOf(value).remove('.').substring(0, validLength);
        else returnValue = String.valueOf(value).remove('.').leftPad(validLength, '0');
        return returnValue;
    }

    private static String genValueAsDecimal(String value, Integer validLength){
        if(value == null) value = '0';
        if(value.length() > validLength) value = value.substring(0, validLength);
        else value = value.leftPad(validLength, '0');
        return removeAccents(value);
    }

    public static List<Invoice__c> queryInvoiceExportFields(Set<Id> invoiceIds){
        return invoices = [SELECT Id, Name, TotalWithVat__c, VAT_Amount__c, InvoiceTerm__c, InvoiceDate__c, InvoiceNumber__c, Avoir__c, OI_Number__c, BU__c, Account__r.Centre_profit_partenaire__c, Account__r.PartnerCompany_Code__c, VatRate__c, TotalExcludingVat__c,
            (select id, Insertion__c, TotalExcludingVat__c, VAT_Amount__c, Ordre_Interne__c from InvoiceItems__r)
            FROM Invoice__c
            WHERE Id IN :invoiceIds];
    }
    
    private static String removeAccents(String source){
        source = source.replaceAll('[èéêë]','e');
        source = source.replaceAll('[àáâãäå]','a');
        source = source.replaceAll('[òóôõöø]','o');
        source = source.replaceAll('[ìíîï]','i');
        source = source.replaceAll('[ùúûü]','u');
        source = source.replaceAll('[ÿ]','y');
        source = source.replaceAll('[ç]','c');
        source = source.replaceAll('[Ç]','C');
        source = source.replaceAll('[°]','-');
        source = source.replaceAll('[Ñ]','N');
        source = source.replaceAll('[ÙÚÛÜ]','U');
        source = source.replaceAll('[ÌÍÎÏ]','I');
        source = source.replaceAll('[ÈÉÊË]','E');
        source = source.replaceAll('[ÒÓÔÕÖØ]','O');
        source = source.replaceAll('[ÀÁÂÃÄÅ]','A');
        if(!source.isAsciiPrintable()) source = source.replaceall('[^\\x00-\\x7F]', '');
        return source;
    }

    private static String getModeReglement(String code){
        Map<String, String> regMap = new Map<String, String>();
        regMap.put('Divers', '00'); 
        regMap.put('Espèces', '01'); 
        regMap.put('Chèque postal', '02'); 
        regMap.put('Chèque Bancaire', '03'); 
        regMap.put('Mandat administratif', '04'); 
        regMap.put('BOC', '05'); 
        regMap.put('LCC non sousmise accept.', '06'); 
        regMap.put('LCC accept.client', '07'); 
        regMap.put('LCC accept.banque', '08'); 
        regMap.put('LCC accept.domiciliée', '09'); 
        regMap.put('Virement postal', '10'); 
        regMap.put('Virement bancaire', '11'); 
        regMap.put('LCR-pap.non soumise accep', '12'); 
        regMap.put('LCR-pap. accept.client', '13'); 
        regMap.put('LCR-pap. accept.banque', '14'); 
        regMap.put('Prélèvement automatique', '15'); 
        regMap.put('BOR-pap.simple', '16'); 
        regMap.put('BOR-pap.accept.banque', '17'); 
        regMap.put('BOR-pap.aval client', '18'); 
        regMap.put('Transfert télégraphique', '19'); 
        regMap.put('LCR magnétique', '20'); 
        regMap.put('BOR magnétique', '21'); 
        regMap.put('LCC émise par client', '22'); 
        regMap.put('LCR-pap.émise par client', '23'); 
        regMap.put('Crédit documentaire', '24'); 
        regMap.put('Virement SWIFT', '25'); 
        regMap.put('Crédit documentaire à vue', '26'); 
        regMap.put('Crédit documentaire avec LC', '27'); 
        regMap.put('Contre remb par le transitaire', '28'); 
        regMap.put('Lettre de crédit', '29');
        regMap.put('Virement commercial', '30');
        return regMap.get(code);
    }
}