force-app/main/default/objects/Account/fields/GenerixCode__c.field-meta.xml
<CustomField>
    <fullName>GenerixCode__c</fullName>
    <externalId>true</externalId>
    <label>Code unique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntracomVatNumber__c.field-meta.xml
<CustomField>
    <fullName>IntracomVatNumber__c</fullName>
    <label>N° TVA Intracommunautaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SapCode__c.field-meta.xml
<CustomField>
    <fullName>SapCode__c</fullName>
    <externalId>true</externalId>
    <label>Code SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingEntity__c/fields/IntracomVatNumber__c.field-meta.xml
<CustomField>
    <fullName>IntracomVatNumber__c</fullName>
    <label>TVA Intracom.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingEntity__c/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCAPTIF&quot;), &quot;Non Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBRP&quot;), &quot;Régie Physique&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBHORSCAPTIF&quot;), &quot;Hors Captif&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBALIMENTAIR&quot;), &quot;Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPART&quot;), &quot;Cashback Webloyalty&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPROG&quot;), &quot;AdEx&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBNIP&quot;), &quot;NIP&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBAUTRES&quot;), &quot;Autres&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCLAB&quot;), &quot;CLAB&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBW2S&quot;), &quot;WEB TO STORE&quot;,
&quot;&quot;

))))))))))</formula>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Category__c )</formula>
    <label>Catégorie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Type__c )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <formula>Opportunity__r.BillingEntity__r.Name</formula>
    <label>Entité de facturation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BUs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Ligne de facture</label>
    <nameField>
        <label>Nom de la ligne de facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Insertion__c.field-meta.xml
<CustomField>
    <fullName>Insertion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insertion</label>
    <referenceTo>Insertion__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AdvertiserContact__c.field-meta.xml
<CustomField>
    <fullName>AdvertiserContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Annonceur</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités (Contact Annonceur)</relationshipLabel>
    <relationshipName>AdvertiserOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AgencyContact__c.field-meta.xml
<CustomField>
    <fullName>AgencyContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Agence</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités (Contact Agence)</relationshipLabel>
    <relationshipName>AgencyOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité de facturation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>BillingEntity__c.Name</field>
            <operation>notContain</operation>
            <value>Maxit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BillingEntity__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CampaignEndDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignEndDate__c</fullName>
    <label>Date de fin théorique</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CampaignStartDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignStartDate__c</fullName>
    <label>Date de début théorique</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CustomerReference__c.field-meta.xml
<CustomField>
    <fullName>CustomerReference__c</fullName>
    <label>Réf. client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activation MD</fullName>
            </value>
            <value>
                <fullName>Activation Online</fullName>
            </value>
            <value>
                <fullName>Adex</fullName>
            </value>
            <value>
                <fullName>Etude et mesure</fullName>
            </value>
            <value>
                <fullName>Frais techniques</fullName>
            </value>
            <value>
                <fullName>Régule</fullName>
            </value>
            <value>
                <fullName>Display Onsite</fullName>
            </value>
            <value>
                <fullName>Forfait Visuels</fullName>
            </value>
            <value>
                <fullName>Promogaming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PricingModel__c.field-meta.xml
<CustomField>
    <fullName>PricingModel__c</fullName>
    <label>Mode de com</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_produit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>Forfait</fullName>
                <default>true</default>
                <label>Forfait</label>
            </value>
            <value>
                <fullName>Prix unitaire</fullName>
            </value>
            <value>
                <fullName>Euros par coupon</fullName>
            </value>
            <value>
                <fullName>Montant</fullName>
            </value>
            <value>
                <fullName>% de la générosité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3W Retail media plateform</fullName>
            </value>
            <value>
                <fullName>Adresses postales</fullName>
            </value>
            <value>
                <fullName>Affichage chariot</fullName>
            </value>
            <value>
                <fullName>Analyse de mixités</fullName>
            </value>
            <value>
                <fullName>Bannière HP Premium 1600x200</fullName>
            </value>
            <value>
                <fullName>bannières multiformats</fullName>
            </value>
            <value>
                <fullName>Bannières order process</fullName>
            </value>
            <value>
                <fullName>Cache antenne</fullName>
            </value>
            <value>
                <fullName>Cash Back</fullName>
            </value>
            <value>
                <fullName>Clab</fullName>
            </value>
            <value>
                <fullName>Concurrence win/lost sur Cdiscount</fullName>
            </value>
            <value>
                <fullName>Echantillons</fullName>
            </value>
            <value>
                <fullName>emailing BtoB</fullName>
            </value>
            <value>
                <fullName>emailing BtoC</fullName>
            </value>
            <value>
                <fullName>Etude Ad hoc</fullName>
            </value>
            <value>
                <fullName>Etude lancement de produit</fullName>
            </value>
            <value>
                <fullName>Etude produit à maturité/en déclin</fullName>
            </value>
            <value>
                <fullName>Frais technique</fullName>
            </value>
            <value>
                <fullName>Frais technique push SMS</fullName>
            </value>
            <value>
                <fullName>Google adsense</fullName>
            </value>
            <value>
                <fullName>Google adx</fullName>
            </value>
            <value>
                <fullName>Google shopping</fullName>
            </value>
            <value>
                <fullName>Habillage de page</fullName>
            </value>
            <value>
                <fullName>Interstitiel</fullName>
            </value>
            <value>
                <fullName>Kakémono</fullName>
            </value>
            <value>
                <fullName>Leaflets</fullName>
            </value>
            <value>
                <fullName>Lien partenaire</fullName>
            </value>
            <value>
                <fullName>Lien sponso Google</fullName>
            </value>
            <value>
                <fullName>Loc data - SMS</fullName>
            </value>
            <value>
                <fullName>Locdata - emailing BtoC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/faeaae_exportTest.cls
@isTest
public class faeaae_exportTest {
    @testSetup static void setup() {
        List<Account> accounts = TestApexDataFactory.createSObjectList('Account', new Map<String,Object>{
          'Name' => new List<String>{'test', 'testAgence', 'testAdvertiser'},
          'BillingStreet'	=> 'Montée de la bonne mère',
          'BillingPostalCode'	=> '13006',
          'BillingCity'	=> 'Marseille',
          'BillingCountry' => 'France',
          'BillingCountryCode' => 'FR',
          'Type'	=> new List<String>{'Adex', 'Adex', 'Annonceur'},
          'GenerixCode__c'=> new List<String>{'R55555', 'GNX1234', 'GNX12340'},
          'SapCode__c'	=> new List<String>{'test123', 'SAP1234', 'SAP12340'},
          'IntracomVatNumber__c'	=> new List<String>{'FR00999999999', 'FR12341231234', 'FR12341231234'},
          'Siret__c'	=> new List<String>{'99999999999999', 'SIRET123401235', 'SIRET123401234'},
          'Siren__c'	=> '123456789'
        }, 3);

        BillingEntity__c billEnt = (BillingEntity__c)TestApexDataFactory.createSObject('BillingEntity__c', new Map<String,Object>{
            'Name' => 'Infinity Advertising'
        });

        Account advertiser = (Account)TestApexDataFactory.createSObject('Account', new Map<String,Object>{
            'Name'	=> 'Advertisername1',
            'BillingStreet'	=> 'Montée de la bonne mère',
            'BillingCity'	=> 'Marseille',
            'BillingCountry' => 'France',
            'Siret__c'	=> 'SIRET123401615',
            'Siren__c'	=> '123156789',
            'BillingPostalCode'	=> '13006'
        });

        Product2 product = (Product2)TestApexDataFactory.createSObject('Product2', new Map<String,Object>{
			'Name'	=> 'test1',     
            'Type__c'	=> 'Display', 
            'PricingModel__c'	=> 'Prix Unitaire', 
            'Category__c' 	=> 'Animation', 
            'BU__c'	=> 'ESPPUBALIMENTAIR', 
            'CampaignType__c'	=> 'Open Order',
            'isactive'	=> true
        });
        
        Opportunity opportunity = (Opportunity)TestApexDataFactory.createSObject('Opportunity', new Map<String,Object>{
        	'BillingEntity__r'	=> new Map<String,Object>{
             	'Name' => 'Billing Entity Name'
             },
        	'CampaignStartDate__c'	=> Date.newInstance(2020, 2, 17),
        	'CampaignEndDate__c'	=> Date.newInstance(2020, 2, 25),
        	'AdvertiserContact__r'	=> new Map<String,Object>{
             	'LastName' => 'Contact Advertiser'
            },
        	'AgencyContact__r'	=> new Map<String,Object>{
             	'LastName' => 'Contact Agence'
            },
        	'CustomerReference__c'	=> 'RefClient',
        	'CloseDate'	=> Date.newInstance(1960, 2, 17),
        	'StageName' => 'Proposition push',
        	'Name'	=> 'TestOpp'
        });
        
        List<Insertion__c> insertions = TestApexDataFactory.createSObjectList('Insertion__c', new Map<String,Object>{
          'Opportunity__c' => opportunity.Id,
          'Product__c'	=> product.Id,
          'CampaignNumber__c'	=> '1',
          'StartDate__c' => Date.newInstance(2010, 3, 17),
          'EndDate__c' => Date.newInstance(2010, 3, 18)
        }, 3);
        
         InvoiceItem__c mainInvoiceItem = (InvoiceItem__c)TestApexDataFactory.createSObject('InvoiceItem__c', new Map<String,Object>{
        	'Quantity__c'	=> 50,
            'Product__c'	=> product.Id,
            'Insertion__c'	=> insertions[0].Id,
            'TotalExcludingVat__c'	=> 500,
            'Invoice__r'	=> new Map<String,Object>{
                'Account__c'	=> accounts[0].Id,
                'Name'	=>	'test',
                'Opportunity__c'	=> opportunity.Id,
                'InvoiceDate__c'	=> System.today(),
                'advertiser__c'	=> advertiser.Id
            }
        });

        List<InvoiceItem__c> invoiceItems = TestApexDataFactory.createSObjectList('InvoiceItem__c', new Map<String,Object>{
        	'Quantity__c'	=> 50,
            'Product__c'	=> product.Id,
            'TotalExcludingVat__c'	=> 500,
            'Insertion__c'	=> insertions[0].Id,
            'Invoice__r'	=> new Map<String,Object>{
                'Account__c'	=> accounts[0].Id,
                'Name'	=>	'test Fac {!index}',
                'Opportunity__c'	=> opportunity.Id,
                'InvoiceDate__c'	=> System.today(),
                'OriginalInvoiceNumber__c'	=> mainInvoiceItem.Invoice__r.Id,
                'advertiser__c'	=> advertiser.Id
            }
        }, 3);
        
        Profile stdProfile = [SELECT Id FROM Profile LIMIT 1];
        User user = (User)TestApexDataFactory.createSObject('User', new Map<String,Object>{
            'Alias'	=> 'standt',
            'Email'	=> 'standarduser@testorg.com',
            'EmailEncodingKey'	=> 'UTF-8',
            'LastName'	=> 'Testing',
            'LanguageLocaleKey'	=> 'en_US',
            'LocaleSidKey'	=> 'en_US',
            'ProfileId'	=> stdProfile.Id,
            'TimeZoneSidKey'	=> 'America/Los_Angeles',
            'UserName'	=> 'standardtestuser@123testorg.com'
        });
       
        Document document = (Document)TestApexDataFactory.createSObject('Document', new Map<String,Object>{
        	'body'	=> Blob.valueOf('a'),
            'folderid'	=> user.Id,
            'name'	=> 'a.txt'
        });
        
        ProvisionNumber__c provisionNumber = (ProvisionNumber__c)TestApexDataFactory.createSObject('ProvisionNumber__c', new Map<String,Object>{
        	'counter__c'	=> 1
        });
                
		List<Contact> contacts = TestApexDataFactory.createSObjectList('Contact', new Map<String,Object>{
        	'LastName'	=> new List<String>{'Contact Agence', 'Contact Advertiser'}
        }, 2);
    }
    
    @isTest
    public static void faeaae_exportTest() {
        List<Invoice__c> invList = [SELECT Id FROM Invoice__c];
        List<Invoice__c> schedInvList = [SELECT Id, Name, TotalWithVat__c, VAT_Amount__c, BU__c, Account__r.Centre_profit_partenaire__c, Account__r.PartnerCompany_Code__c, VatRate__c, TotalExcludingVat__c,
                    (select id, Insertion__c, TotalExcludingVat__c, Ordre_Interne__c from InvoiceItems__r)
                    FROM Invoice__c];
        
        ApexPages.StandardSetController a = new ApexPages.StandardSetController(invList);
        a.setSelected(invList);
        faeaae_export Controller = new faeaae_export(a);
        faeaae_export.exportFae();
        faeaae_export.exportAae();
        faeaae_export.exportAaeSched(schedInvList);
        faeaae_export.exportFaeSched(schedInvList);
    }
}