force-app/main/default/objects/Account/fields/GenerixCode__c.field-meta.xml
<CustomField>
    <fullName>GenerixCode__c</fullName>
    <externalId>true</externalId>
    <label>Code unique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntracomVatNumber__c.field-meta.xml
<CustomField>
    <fullName>IntracomVatNumber__c</fullName>
    <label>N° TVA Intracommunautaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offre éligible</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ne pas mettre de filtres sur ce champ &gt; bug quand passage en OI signé</description>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit d&apos;opération</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OI facturé</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
            <value>
                <fullName>Signé</fullName>
            </value>
            <value>
                <fullName>Signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI clôturé</fullName>
            </value>
            <value>
                <fullName>OI signé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Payeur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>AccountInvoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Advertiser__c.field-meta.xml
<CustomField>
    <fullName>Advertiser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annonceur</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Factures (Annonceur)</relationshipLabel>
    <relationshipName>AdvertiserInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Avoir__c.field-meta.xml
<CustomField>
    <fullName>Avoir__c</fullName>
    <formula>NOT(ISBLANK( OriginalInvoiceNumber__c ))</formula>
    <label>Avoir ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <formula>Opportunity__r.BillingEntity__r.Name</formula>
    <label>Entité de facturation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Date Facture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <externalId>true</externalId>
    <label>N° Facture</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTerm__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTerm__c</fullName>
    <label>Date d&apos;échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OriginalInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>OriginalInvoiceNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Facture annulée d&apos;où provient l&apos;avoir</inlineHelpText>
    <label>Facture d&apos;origine</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>validated</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Annulée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Today__c.field-meta.xml
<CustomField>
    <fullName>Today__c</fullName>
    <formula>TODAY()</formula>
    <label>Today</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalExcludingVat__c.field-meta.xml
<CustomField>
    <fullName>TotalExcludingVat__c</fullName>
    <label>Total HT</label>
    <summarizedField>InvoiceItem__c.TotalExcludingVat__c</summarizedField>
    <summaryForeignKey>InvoiceItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalWithVat__c.field-meta.xml
<CustomField>
    <fullName>TotalWithVat__c</fullName>
    <formula>(TotalExcludingVat__c *  VatRate__c) + TotalExcludingVat__c</formula>
    <label>Total TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <formula>TotalWithVat__c -  TotalExcludingVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Ligne de facture</label>
    <nameField>
        <label>Nom de la ligne de facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Insertion__c.field-meta.xml
<CustomField>
    <fullName>Insertion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insertion</label>
    <referenceTo>Insertion__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>invoiceitems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>invoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/TotalExcludingVat__c.field-meta.xml
<CustomField>
    <fullName>TotalExcludingVat__c</fullName>
    <label>Total HT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/VAT_Amount__c.field-meta.xml
<CustomField>
    <fullName>VAT_Amount__c</fullName>
    <formula>TotalExcludingVat__c *  Invoice__r.VatRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Montant TVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/InvoiceNumber__c/InvoiceNumber__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>InvoiceNumber</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/AutoOppId__c.field-meta.xml
<CustomField>
    <fullName>AutoOppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Numéro d&apos;opportunité</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité de facturation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>BillingEntity__c.Name</field>
            <operation>notContain</operation>
            <value>Maxit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BillingEntity__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Developer_Name__c</fullName>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record type Developer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/invoice_controller.cls
public with sharing class invoice_controller {
    public final Invoice__c Invoice;
    public final List<invoiceDetail> invoiceDetails;

    public invoice_controller() {
        invoiceDetails = new List<invoiceDetail>();

        Invoice = [SELECT 
                    Id, 
                    Status__c,
                    Today__c,
                    Name,
                    Avoir__c,
                    OriginalInvoiceNumber__r.InvoiceNumber__c,
                    Opportunity__r.AutoOppId__c,
                    Opportunity__r.Name,
                    Advertiser__r.Name,
                    Advertiser__r.GenerixCode__c,
                    Advertiser__r.BillingStreet,
                    Advertiser__r.BillingPostalCode,
                    Advertiser__r.BillingCity,
                    Advertiser__r.BillingCountry,
                    Advertiser__r.IntracomVatNumber__c,
                    Account__r.Name,
                    Account__r.GenerixCode__c,
                    Invoice__c.Account__r.BillingStreet,
                    Account__r.BillingCity,
                    Account__r.BillingPostalCode,
                    Account__r.BillingCountry,
                    Account__r.IntracomVatNumber__c,
                    TotalExcludingVat__c,
                    VAT_Amount__c,
                    TotalWithVat__c,
                    InvoiceTerm__c,
                    InvoiceDate__c,
                    Opportunity__r.Developer_Name__c,
                    Opportunity__r.BillingEntity__r.ioConditions__c,
                    (SELECT 
                        Id, 
                        Insertion__r.OpportunityProduct__r.Id,
                        Insertion__r.OpportunityProduct__r.Name,
                        Insertion__r.OpportunityProduct__r.StartDate__c,
                        Insertion__r.OpportunityProduct__r.EndDate__c,
                        Insertion__r.OpportunityProduct__r.Description__c
                    FROM InvoiceItems__r) 
                FROM Invoice__c 
                WHERE Id = :ApexPages.currentPage().getParameters().get('id')];

        Map<Id, Product__c> products = new Map<ID, Product__c>();
        
        for(InvoiceItem__c item : invoice.invoiceitems__r){
            products.put(item.Insertion__r.OpportunityProduct__c, item.Insertion__r.OpportunityProduct__r);
        }
        
        //[SELECT Id, StartDate__c, EndDate__c, Description__c, Name FROM Product__c WHERE Invoice__c =:invoice.Id]);

        for(AggregateResult ar : [SELECT Insertion__r.OpportunityProduct__c opportunityProduct__c, SUM(TotalExcludingVat__c) totalExcludingVat 
                                    FROM InvoiceItem__c 
                                    WHERE Invoice__c =: invoice.Id 
                                    GROUP BY Insertion__r.OpportunityProduct__c]){

            Product__c product = products.get((String) ar.get('opportunityProduct__c'));
            
            invoiceDetail invoiceDetail = new invoiceDetail();
            invoiceDetail.totalExcludingVat = (Double) ar.get('totalExcludingVat');
            if(product != null){
                invoiceDetail.opportunityProductName = product.Name;
                if(product.StartDate__c != null){
                    invoiceDetail.startDate = product.StartDate__c.format();
                }
                if(product.EndDate__c != null){
                    invoiceDetail.endDate = product.EndDate__c.format();
                }            
                invoiceDetail.description = product.Description__c;
            }
            invoiceDetails.add(invoiceDetail);
        }
    }

    public Invoice__c getInvoice(){
        return Invoice;
    }

    public List<invoiceDetail> getInvoiceDetails (){
        return invoiceDetails;
    }

    public class invoiceDetail{
        public String opportunityProductName {get; set;}
        public String description {get; set;}
        public String startDate {get; set;}
        public String endDate {get; set;}
        public Double totalExcludingVat {get; set;}
    }
}