force-app/main/default/objects/Account/fields/GenerixCode__c.field-meta.xml
<CustomField>
    <fullName>GenerixCode__c</fullName>
    <externalId>true</externalId>
    <label>Code unique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntracomVatNumber__c.field-meta.xml
<CustomField>
    <fullName>IntracomVatNumber__c</fullName>
    <label>N° TVA Intracommunautaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SapCode__c.field-meta.xml
<CustomField>
    <fullName>SapCode__c</fullName>
    <externalId>true</externalId>
    <label>Code SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingEntity__c/fields/IntracomVatNumber__c.field-meta.xml
<CustomField>
    <fullName>IntracomVatNumber__c</fullName>
    <label>TVA Intracom.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingEntity__c/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCAPTIF&quot;), &quot;Non Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBRP&quot;), &quot;Régie Physique&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBHORSCAPTIF&quot;), &quot;Hors Captif&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBALIMENTAIR&quot;), &quot;Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPART&quot;), &quot;Cashback Webloyalty&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPROG&quot;), &quot;AdEx&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBNIP&quot;), &quot;NIP&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBAUTRES&quot;), &quot;Autres&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCLAB&quot;), &quot;CLAB&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBW2S&quot;), &quot;WEB TO STORE&quot;,
&quot;&quot;

))))))))))</formula>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Category__c )</formula>
    <label>Catégorie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Type__c )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <formula>Opportunity__r.BillingEntity__r.Name</formula>
    <label>Entité de facturation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BUs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Ligne de facture</label>
    <nameField>
        <label>Nom de la ligne de facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Insertion__c.field-meta.xml
<CustomField>
    <fullName>Insertion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insertion</label>
    <referenceTo>Insertion__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AdvertiserContact__c.field-meta.xml
<CustomField>
    <fullName>AdvertiserContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Annonceur</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités (Contact Annonceur)</relationshipLabel>
    <relationshipName>AdvertiserOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AgencyContact__c.field-meta.xml
<CustomField>
    <fullName>AgencyContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Agence</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunités (Contact Agence)</relationshipLabel>
    <relationshipName>AgencyOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité de facturation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>BillingEntity__c.Name</field>
            <operation>notContain</operation>
            <value>Maxit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BillingEntity__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CampaignEndDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignEndDate__c</fullName>
    <label>Date de fin théorique</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CampaignStartDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignStartDate__c</fullName>
    <label>Date de début théorique</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CustomerReference__c.field-meta.xml
<CustomField>
    <fullName>CustomerReference__c</fullName>
    <label>Réf. client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activation MD</fullName>
            </value>
            <value>
                <fullName>Activation Online</fullName>
            </value>
            <value>
                <fullName>Adex</fullName>
            </value>
            <value>
                <fullName>Etude et mesure</fullName>
            </value>
            <value>
                <fullName>Frais techniques</fullName>
            </value>
            <value>
                <fullName>Régule</fullName>
            </value>
            <value>
                <fullName>Display Onsite</fullName>
            </value>
            <value>
                <fullName>Forfait Visuels</fullName>
            </value>
            <value>
                <fullName>Promogaming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PricingModel__c.field-meta.xml
<CustomField>
    <fullName>PricingModel__c</fullName>
    <label>Mode de com</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_produit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>Forfait</fullName>
                <default>true</default>
                <label>Forfait</label>
            </value>
            <value>
                <fullName>Prix unitaire</fullName>
            </value>
            <value>
                <fullName>Euros par coupon</fullName>
            </value>
            <value>
                <fullName>Montant</fullName>
            </value>
            <value>
                <fullName>% de la générosité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3W Retail media plateform</fullName>
            </value>
            <value>
                <fullName>Adresses postales</fullName>
            </value>
            <value>
                <fullName>Affichage chariot</fullName>
            </value>
            <value>
                <fullName>Analyse de mixités</fullName>
            </value>
            <value>
                <fullName>Bannière HP Premium 1600x200</fullName>
            </value>
            <value>
                <fullName>bannières multiformats</fullName>
            </value>
            <value>
                <fullName>Bannières order process</fullName>
            </value>
            <value>
                <fullName>Cache antenne</fullName>
            </value>
            <value>
                <fullName>Cash Back</fullName>
            </value>
            <value>
                <fullName>Clab</fullName>
            </value>
            <value>
                <fullName>Concurrence win/lost sur Cdiscount</fullName>
            </value>
            <value>
                <fullName>Echantillons</fullName>
            </value>
            <value>
                <fullName>emailing BtoB</fullName>
            </value>
            <value>
                <fullName>emailing BtoC</fullName>
            </value>
            <value>
                <fullName>Etude Ad hoc</fullName>
            </value>
            <value>
                <fullName>Etude lancement de produit</fullName>
            </value>
            <value>
                <fullName>Etude produit à maturité/en déclin</fullName>
            </value>
            <value>
                <fullName>Frais technique</fullName>
            </value>
            <value>
                <fullName>Frais technique push SMS</fullName>
            </value>
            <value>
                <fullName>Google adsense</fullName>
            </value>
            <value>
                <fullName>Google adx</fullName>
            </value>
            <value>
                <fullName>Google shopping</fullName>
            </value>
            <value>
                <fullName>Habillage de page</fullName>
            </value>
            <value>
                <fullName>Interstitiel</fullName>
            </value>
            <value>
                <fullName>Kakémono</fullName>
            </value>
            <value>
                <fullName>Leaflets</fullName>
            </value>
            <value>
                <fullName>Lien partenaire</fullName>
            </value>
            <value>
                <fullName>Lien sponso Google</fullName>
            </value>
            <value>
                <fullName>Loc data - SMS</fullName>
            </value>
            <value>
                <fullName>Locdata - emailing BtoC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AaeBatchExportTest.cls
@isTest
public class AaeBatchExportTest {
    // static TestDataFactory t;
    // static { t = new TestDataFactory(); }
    
    /*
    @testSetup static void setup() {
        List<Account> accounts = TestApexDataFactory.createSObjectList('Account', new Map<String,Object>{
            'Name' => new List<String>{'test', 'testAgence', 'testAdvertiser'},
                'BillingStreet'	=> 'Montée de la bonne mère',
                'BillingPostalCode'	=> '13006',
                'BillingCity'	=> 'Marseille',
                'BillingCountryCode' => 'FR',
                'Type'	=> new List<String>{'Adex', 'Adex', 'Annonceur'},
                    'GenerixCode__c'=> new List<String>{'R55555', 'GNX1234', 'GNX12340'},
                        'SapCode__c'	=> new List<String>{'test123', 'SAP1234', 'SAP12340'},
                            'IntracomVatNumber__c'	=> new List<String>{'FR00999999999', 'FR12341231234', 'FR12341231234'},
                                'Siret__c'	=> new List<String>{'99999999999999', 'SIRET123401235', 'SIRET123401234'},
                                    'Siren__c'	=> '123456789'
                                    }, 3);
        
        Product2 product = (Product2)TestApexDataFactory.createSObject('Product2', new Map<String,Object>{
            'Name'	=> 'test',     
                'Type__c'	=> 'Display', 
                'PricingModel__c'	=> 'Prix Unitaire', 
                'Category__c' 	=> 'Animation', 
  //              'BU__c'	=> 'ESPPUBCAPTIF', 
                'CampaignType__c'	=> 'Open Order',
                'isactive'	=> true
                });

        BillingEntity__c billEnt = (BillingEntity__c)TestApexDataFactory.createSObject('BillingEntity__c', new Map<String,Object>{
            'Name' => 'Infinity Advertising'
        });
        
        Opportunity opportunity = (Opportunity)TestApexDataFactory.createSObject('Opportunity', new Map<String,Object>{
            'BillingEntity__r'	=> new Map<String,Object>{
                'Name' => 'Relevanc'
                    },
                        'CampaignStartDate__c'	=> Date.newInstance(2020, 2, 17),
                        'CampaignEndDate__c'	=> Date.newInstance(2020, 2, 25),
                        'AdvertiserContact__r'	=> new Map<String,Object>{
                            'LastName' => 'Contact Advertiser'
                                },
                                    'AgencyContact__r'	=> new Map<String,Object>{
                                        'LastName' => 'Contact Agence'
                                            },
                                                'CustomerReference__c'	=> 'RefClient',
                                                'CloseDate'	=> Date.newInstance(1960, 2, 17),
                                                'StageName' => 'Proposition push',
                                                'Name'	=> 'TestOpp'
                                                });
        
        List<Insertion__c> insertions = TestApexDataFactory.createSObjectList('Insertion__c', new Map<String,Object>{
            'Opportunity__c' => opportunity.Id,
                'Product__c'	=> product.Id,
                'CampaignNumber__c'	=> '1',
                'StartDate__c' => Date.newInstance(2010, 3, 17),
                'EndDate__c' => Date.newInstance(2010, 3, 18)
                }, 3);
        
        InvoiceItem__c mainInvoiceItem = (InvoiceItem__c)TestApexDataFactory.createSObject('InvoiceItem__c', new Map<String,Object>{
            'Quantity__c'	=> 50,
                'Product__c'	=> product.Id,
                'Insertion__c'	=> insertions[0].Id,
                'TotalExcludingVat__c' => -50000,
                'Invoice__r'	=> new Map<String,Object>{
                    'Account__c'	=> accounts[0].Id,
                        'Name'	=>	'test',
                        'Opportunity__c'	=> opportunity.Id,
                        'InvoiceDate__c'	=> System.today(),
                        'Status__c'			=> 'draft'
                        }
        });
        
        List<InvoiceItem__c> invoiceItems = TestApexDataFactory.createSObjectList('InvoiceItem__c', new Map<String,Object>{
            'Quantity__c'	=> 50,
                'Product__c'	=> product.Id,
                'Insertion__c'	=> insertions[0].Id,
                'TotalExcludingVat__c' => -50000,
                'Invoice__r'	=> new Map<String,Object>{
                    'Account__c'	=> accounts[0].Id,
                        'Name'	=>	'test Fac {!index}',
                        'Opportunity__c'	=> opportunity.Id,
                        'InvoiceDate__c'	=> System.today(),
                        'Status__c'			=> 'draft',
                        'OriginalInvoiceNumber__c'	=> mainInvoiceItem.Invoice__r.Id
                        }
        }, 3);
        
        Profile stdProfile = [SELECT Id FROM Profile LIMIT 1];
        User user = (User)TestApexDataFactory.createSObject('User', new Map<String,Object>{
            'Alias'	=> 'standt',
                'Email'	=> 'standarduser@testorg.com',
                'EmailEncodingKey'	=> 'UTF-8',
                'LastName'	=> 'Testing',
                'LanguageLocaleKey'	=> 'en_US',
                'LocaleSidKey'	=> 'en_US',
                'ProfileId'	=> stdProfile.Id,
                'TimeZoneSidKey'	=> 'America/Los_Angeles',
                'UserName'	=> 'standardtestuser@123testorg.com'
                });
        
        ProvisionNumber__c provisionNumber = (ProvisionNumber__c)TestApexDataFactory.createSObject('ProvisionNumber__c', new Map<String,Object>{
            'counter__c'	=> 1
                });
        
        List<Contact> contacts = TestApexDataFactory.createSObjectList('Contact', new Map<String,Object>{
            'LastName'	=> new List<String>{'Contact Agence', 'Contact Advertiser'}
        }, 2);
    }
    */
    
    static testMethod void testMethod1(){
        
        Test.startTest();
        Account account = new Account(Name = 'test', BillingStreet =  '1 rue Test', BillingPostalCode = '75001', BillingCity = 'Paris', GenerixCode__c='R55555', SapCode__c='test123', BillingCountryCode = 'FR', IntracomVatNumber__c = 'FR00999999999', Siret__c = '99999999999999', Siren__c='123456789');
        insert account;
        BillingEntity__c be =  new BillingEntity__c(Name = 'Relevanc', LastInvoiceNumber__c = 1, InvoicePrefix__c = '65');
        insert be;
        BillingEntity__c be2 =  new BillingEntity__c(Name = 'Infinity Advertising', LastInvoiceNumber__c = 1, InvoicePrefix__c = '65');
        insert be2;
        
        Contact contact = new Contact(AssistantName='Test1', AccountId = account.id,LastName='Test2');
        insert contact;
        
        Opportunity opp = new Opportunity(Name = 'opp test', AccountId = account.id, CloseDate = Date.today(), StageName = 'Proposition push',InvoicedAccount__c = 'Annonceur', BU__c = 'ESPPUBALIMENTAIR',BillingEntity__c =be.Id,	AdvertiserContact__c=contact.id,AgencyContact__c = contact.id);
        Opportunity opp2 = new Opportunity(Name = 'opp test2', AccountId = account.id, CloseDate = Date.today(), StageName = 'Proposition push',InvoicedAccount__c = 'Annonceur', BU__c = 'ESPPUBALIMENTAIR',BillingEntity__c =be2.Id,	AdvertiserContact__c=contact.id ,AgencyContact__c = contact.id);
        
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(opp);
        oppList.add(opp2);
        insert oppList;
        
        Invoice__c inv1 =  new Invoice__c(
            Account__c = account.Id, 
            Name='test1', 
            Opportunity__c=oppList[0].Id, 
            InvoiceDate__c=System.today(),
            Status__c = 'draft'
        );

        Invoice__c inv2 =  new Invoice__c(
            Account__c = account.Id, 
            Name='test', 
            Opportunity__c=oppList[0].Id, 
            InvoiceDate__c=System.today(),
            Status__c = 'draft'
        );

        List<Invoice__c> invList = new List<Invoice__c>();
        invList.add(inv1);
        invList.add(inv2);
        insert invList;
        invList[1].OriginalInvoiceNumber__c = invList[0].Id;
        update invList;
        
        AaeBatchExport batch = new AaeBatchExport();
        Id batchId = Database.executeBatch(batch);
        
        AaeBatchExport schedule = new AaeBatchExport();
        System.schedule('test','0 0 8 13 2 ?', schedule);
        Id batchJobId = Database.executeBatch(new AaeBatchExport(), 8);
        Test.stopTest();
    }
}