force-app/main/default/objects/Account/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA signé</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Signed_IO__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.CloseDate</field>
        <operation>greaterOrEqual</operation>
        <value>1/1/2022</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.CloseDate</field>
        <operation>lessOrEqual</operation>
        <value>12/31/2022</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/CampaignNumber__c.field-meta.xml
<CustomField>
    <fullName>CampaignNumber__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de campagne</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>Utilisé en reporting</description>
    <formula>TEXT( Product__r.Medium__c )</formula>
    <label>Support</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/NewInsertion__c.field-meta.xml
<CustomField>
    <fullName>NewInsertion__c</fullName>
    <formula>IF( 
CreatedById = Opportunity__r.Owner.Id , 
false, true
)</formula>
    <label>Insertion manuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/OpportunityProduct__c.field-meta.xml
<CustomField>
    <fullName>OpportunityProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offre éligible</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/OrderReference__c.field-meta.xml
<CustomField>
    <fullName>OrderReference__c</fullName>
    <label>Réf. Bon de commande</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ne pas mettre de filtres sur ce champ &gt; bug quand passage en OI signé</description>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit d&apos;opération</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OI facturé</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
            <value>
                <fullName>Signé</fullName>
            </value>
            <value>
                <fullName>Signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI clôturé</fullName>
            </value>
            <value>
                <fullName>OI signé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Targeting__c.field-meta.xml
<CustomField>
    <fullName>Targeting__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Targeting__c )</formula>
    <label>Ciblage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>CPM ou PU</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AutoOppId__c.field-meta.xml
<CustomField>
    <fullName>AutoOppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Numéro d&apos;opportunité</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ClosedAmount__c.field-meta.xml
<CustomField>
    <fullName>ClosedAmount__c</fullName>
    <description>Utilisé pour le reporting</description>
    <label>Montant clôturé</label>
    <summarizedField>Insertion__c.Revenue__c</summarizedField>
    <summaryFilterItems>
        <field>Insertion__c.Status__c</field>
        <operation>equals</operation>
        <value>Clôturé, OI facturé</value>
    </summaryFilterItems>
    <summaryForeignKey>Insertion__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ClosedAmountNotInvoiced__c.field-meta.xml
<CustomField>
    <fullName>ClosedAmountNotInvoiced__c</fullName>
    <label>Montant clôturé sans facture</label>
    <summarizedField>Insertion__c.Revenue__c</summarizedField>
    <summaryFilterItems>
        <field>Insertion__c.Status__c</field>
        <operation>equals</operation>
        <value>Clôturé</value>
    </summaryFilterItems>
    <summaryForeignKey>Insertion__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ControledAmount__c.field-meta.xml
<CustomField>
    <fullName>ControledAmount__c</fullName>
    <label>Montant contrôlé</label>
    <summarizedField>Insertion__c.Revenue__c</summarizedField>
    <summaryFilterItems>
        <field>Insertion__c.Status__c</field>
        <operation>equals</operation>
        <value>Signé/contrôlé</value>
    </summaryFilterItems>
    <summaryForeignKey>Insertion__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InvoicedAmount__c.field-meta.xml
<CustomField>
    <fullName>InvoicedAmount__c</fullName>
    <label>Montant facturé</label>
    <summarizedField>Insertion__c.Revenue__c</summarizedField>
    <summaryFilterItems>
        <field>Insertion__c.Status__c</field>
        <operation>equals</operation>
        <value>OI facturé</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Insertion__c.Free__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Insertion__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Targeting__c.field-meta.xml
<CustomField>
    <fullName>Targeting__c</fullName>
    <inlineHelpText>Champ non retranscrit dans l&apos;OI</inlineHelpText>
    <label>Ciblage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/PricingModel__c.field-meta.xml
<CustomField>
    <fullName>PricingModel__c</fullName>
    <label>Mode de com</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_de_produit__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>Forfait</fullName>
                <default>true</default>
                <label>Forfait</label>
            </value>
            <value>
                <fullName>Prix unitaire</fullName>
            </value>
            <value>
                <fullName>Euros par coupon</fullName>
            </value>
            <value>
                <fullName>Montant</fullName>
            </value>
            <value>
                <fullName>% de la générosité</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Targeting__c.field-meta.xml
<CustomField>
    <fullName>Targeting__c</fullName>
    <label>Ciblage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>data</fullName>
            </value>
            <value>
                <fullName>Jumeaux transactionnels</fullName>
            </value>
            <value>
                <fullName>personae</fullName>
            </value>
            <value>
                <fullName>rotation générale</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Prix Unitaire</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpportunityClosingController.cls
public class OpportunityClosingController {
    
    @AuraEnabled
    public static List<Opportunity> getOpportunities() {
        return [SELECT Id, Name, AutoOppId__c, Account.Name, Owner.Name, Amount, ControledAmount__c, ClosedAmount__c, ClosedAmountNotInvoiced__c,
                InvoicedAmount__c,
                (SELECT Id, StartDate__c, EndDate__c, Volume__c, Revenue__c, Status__c, OpportunityProduct__c, Opportunity__c, Product__c, CampaignNumber__c, 
                 OrderReference__c, OpportunityProduct__r.Name, OpportunityProduct__r.UnitPrice__c, OpportunityProduct__r.PricingModel__c, 
                 NewInsertion__c, Product__r.Devices__c, Product__r.Targeting__c, Product__r.Medium__c, Product__r.Type__c, Product__r.PricingModel__c,
                 UnitPrice__c, Free__c, OpportunityProduct__r.Type__c, OpportunityProduct__r.Offert__c
                 FROM Insertions__r) 
                FROM Opportunity
                WHERE Id IN (Select Opportunity__c from Insertion__c WHERE Status__c in ('Signé','Signé/contrôlé','Clôturé','OI facturé'))];
    }
    
    @AuraEnabled
    public static void updateData(String data, String objectType) {
        switch on (objectType) {
            when 'Insertion__c' {
                update (List<Insertion__c>) JSON.deserialize(data, List<Insertion__c>.class);
            }
            when else {
                system.debug('default');
            }
        }
    }
        
}