force-app/main/default/objects/Account/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA signé</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.Signed_IO__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.CloseDate</field>
        <operation>greaterOrEqual</operation>
        <value>1/1/2022</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Opportunity.CloseDate</field>
        <operation>lessOrEqual</operation>
        <value>12/31/2022</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Category__c )</formula>
    <label>Catégorie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>Utilisé en reporting</description>
    <formula>TEXT( Product__r.Medium__c )</formula>
    <label>Support</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ne pas mettre de filtres sur ce champ &gt; bug quand passage en OI signé</description>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit d&apos;opération</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>Product__r.Rate__c</formula>
    <label>Taux Régie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Date de début</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OI facturé</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
            <value>
                <fullName>Signé</fullName>
            </value>
            <value>
                <fullName>Signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI clôturé</fullName>
            </value>
            <value>
                <fullName>OI signé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Targeting__c.field-meta.xml
<CustomField>
    <fullName>Targeting__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Targeting__c )</formula>
    <label>Ciblage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Type__c )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agence</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunités (Agence)</relationshipLabel>
    <relationshipName>AgencyOpportunies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InvoicedAccount__c.field-meta.xml
<CustomField>
    <fullName>InvoicedAccount__c</fullName>
    <label>Payeur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annonceur</fullName>
                <default>true</default>
                <label>Annonceur</label>
            </value>
            <value>
                <fullName>Agence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Targeting__c.field-meta.xml
<CustomField>
    <fullName>Targeting__c</fullName>
    <inlineHelpText>Champ non retranscrit dans l&apos;OI</inlineHelpText>
    <label>Ciblage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AAFCreatorController.cls
public with sharing class AAFCreatorController {
    @AuraEnabled
    public static List<Insertion__c> getAAFInput(String dateString) {
        //Date permettant de trier les Insertions correspondantes
        Date targetDate = Date.newInstance(Integer.valueOf(dateString.split('-')[0]), Integer.valueOf(dateString.split('-')[1]), 1);
        system.debug(targetDate);
        return [SELECT Id, StartDate__c, EndDate__c, Revenue__c, Product__r.Type__c,
                                       Product__r.Targeting__c, Product__r.Medium__c, Product__r.Category__c,
                					   Product__r.Rate__c, Opportunity__r.InvoicedAccount__c, Opportunity__r.Owner.Name,
                					   Opportunity__r.Agency__r.Name, Opportunity__r.Account.Name
                                       FROM Insertion__c
                                       WHERE CALENDAR_MONTH(StartDate__c) =: targetDate.month()
                                       AND CALENDAR_YEAR(StartDate__c) =: targetDate.year()
                                       AND Revenue__c != NULL
                                       AND (Status__c ='Clôturé'
                                       OR Status__c ='OI facturé')
                                       ORDER BY Product__r.Medium__c];
    }
    
    @AuraEnabled
    public static void saveAAF(String fileBlob, String fileTitle){        
        Document docSave = new Document(body = EncodingUtil.base64Decode(fileBlob),
                                        folderid = UserInfo.getUserId(),
                                        name = fileTitle +'.xlsx');
        upsert docSave;
        
        ContentVersion fileSave = new ContentVersion();
        fileSave.ContentLocation = 'S';
        fileSave.VersionData = docSave.Body;
        fileSave.Title = docSave.Name;
        fileSave.PathOnClient = docSave.Name;
        upsert fileSave;
    }
}