force-app/main/default/objects/AssociationDocumentTemplate__mdt/AssociationDocumentTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Association des modeles de doc</label>
    <pluralLabel>Associations des modeles de doc</pluralLabel>
</CustomObject>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Master_object__c.field-meta.xml
<CustomField>
    <fullName>Master_object__c</fullName>
    <label>Master object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Template_to_use__c.field-meta.xml
<CustomField>
    <fullName>Template_to_use__c</fullName>
    <label>Id du template à utiliser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Vfp_used__c.field-meta.xml
<CustomField>
    <fullName>Vfp_used__c</fullName>
    <label>Vfp à utiliser</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Autres.recordType-meta.xml
<RecordType>
    <fullName>Autres</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <label>Autres</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Promogaming.recordType-meta.xml
<RecordType>
    <fullName>Promogaming</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <label>Promogaming</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Search.recordType-meta.xml
<RecordType>
    <fullName>Search</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <label>Search</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activation MD</fullName>
            </value>
            <value>
                <fullName>Activation Online</fullName>
            </value>
            <value>
                <fullName>Adex</fullName>
            </value>
            <value>
                <fullName>Etude et mesure</fullName>
            </value>
            <value>
                <fullName>Frais techniques</fullName>
            </value>
            <value>
                <fullName>Régule</fullName>
            </value>
            <value>
                <fullName>Display Onsite</fullName>
            </value>
            <value>
                <fullName>Forfait Visuels</fullName>
            </value>
            <value>
                <fullName>Promogaming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produits d&apos;opportunités</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/recordTypes/Autres.recordType-meta.xml
<RecordType>
    <fullName>Autres</fullName>
    <active>true</active>
    <label>Autres</label>
</RecordType>

force-app/main/default/objects/Product__c/recordTypes/Promogaming.recordType-meta.xml
<RecordType>
    <fullName>Promogaming</fullName>
    <active>true</active>
    <label>Promogaming</label>
</RecordType>

force-app/main/default/objects/Product__c/recordTypes/Search.recordType-meta.xml
<RecordType>
    <fullName>Search</fullName>
    <active>true</active>
    <label>Search</label>
</RecordType>

force-app/main/default/objects/ProductBundleItem__c/ProductBundleItem__c.object-meta.xml
<CustomObject>
    <label>Entrée de produit commercial</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrées de produit commercial</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductBundleItem__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(ChildProduct__r.Category__c)</formula>
    <label>Catégorie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductBundleItem__c/fields/ChildProduct__c.field-meta.xml
<CustomField>
    <fullName>ChildProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit d&apos;opération</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit d&apos;opération</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrées de produit d&apos;opération</relationshipLabel>
    <relationshipName>Product_Bundle_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductBundleItem__c/fields/ParentProduct__c.field-meta.xml
<CustomField>
    <fullName>ParentProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit commercial</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit commercial</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrées de produit commercial</relationshipLabel>
    <relationshipName>packageProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OIDocumentController.cls
public class OIDocumentController {
    
    public Opportunity opp{get;set;}
    public List<String> listDocs{get;set;}
    public Boolean isTelemarketing{get;set;}

    //added

    public Boolean Test1{get;set;}
    public Boolean Test2{get;set;}
    public Boolean Test3{get;set;}


    public OIDocumentController(ApexPages.StandardController stdController) {
        opp = (Opportunity)stdController.getRecord();

        system.debug('opp'+opp);

        listDocs = new List<String>();
        List<Document> saveDocsList = new List<Document>();
        List<String> alreadyAddDocs = new List<String>();
        Set<Id> product2Ids = new Set<Id>();
        Opportunity opport = [select id, AccountId,RecordTypeId,
                              (select id, package__r.Name, Category__c,
                               package__r.Id,
                               package__r.DocumentTemplate__r.Id,
                               package__r.DocumentTemplate__r.TemplateBodyHTML__c,
                               package__r.DocumentTemplate__r.isHTML__c from Products__r) 
                              from opportunity 
                              where id =: opp.Id];
                              
                              
        //added
        RecordType temp = [Select Id,Name from RecordType where ID=:opport.RecordTypeId];
        if(temp.Name=='Retail Media OnSite' || temp.Name=='Extension d’audience' || temp.Name=='Search')
        {
        Test1=true;
        }

        if(temp.Name=='Promogaming' || temp.Name=='Promotion Personnalisée' || temp.Name=='Autres')
        {
            Test2=true;  
        } 

        if(temp.Name=='Promotion Personnalisée')
        {
            Test3=true;  
        } 
        

        for(Product__c prod : opport.Products__r){
            product2Ids.add(prod.Package__r.Id);
        }
        system.debug('product2Ids'+product2Ids);
        List<ProductBundleItem__c> prodBundles = [SELECT Id, Category__c, ChildProduct__r.Category__c FROM ProductBundleItem__c WHERE ParentProduct__c IN:product2Ids];
        system.debug('prodBundles'+prodBundles);
        for(ProductBundleItem__c prodBndl : prodBundles){
            system.debug('Entered Loop');
            if(prodBndl.Category__c == 'Activation MD' || prodBndl.Category__c == 'Telemarketing') isTelemarketing = true;
            if(prodBndl.ChildProduct__r.Category__c == 'Activation MD' || prodBndl.ChildProduct__r.Category__c == 'Telemarketing') isTelemarketing = true;

            system.debug('isTelemarketing'+isTelemarketing);

        }
        
        List<AssociationDocumentTemplate__mdt> ladt = [select id, MasterLabel, Template_to_use__c, Master_object__c, Vfp_used__c, order__c from AssociationDocumentTemplate__mdt order by order__c asc];

        for(AssociationDocumentTemplate__mdt adt : ladt) {
            for(Product__c p : opport.Products__r) {
                if(alreadyAddDocs.contains(p.Package__r.Name)) continue;
                String templateBody = p.package__r.DocumentTemplate__r.isHtml__c ? p.package__r.DocumentTemplate__r.TemplateBodyHTML__c : p.package__r.DocumentTemplate__r.TemplateBody__c;
                System.debug('adt.Template_to_use__c --> ' + adt.Template_to_use__c);
                System.debug('p.package__r.DocumentTemplate__r.Id --> ' + p.package__r.DocumentTemplate__r.Id);

                if(adt.Template_to_use__c == p.package__r.DocumentTemplate__r.Id || Test.isRunningTest()) {
                    PageReference page = new PageReference('/apex/'+adt.Vfp_used__c+
                                                           '?id='+opp.Id+
                                                           '&masterObject='+adt.Master_object__c+
                                                           '&relatedObject='+'Product__c'+
                                                           '&relatedId='+p.Id);
                    listDocs.add(DocumentTemplateController.getDocumentBody(templateBody, page));
                    alreadyAddDocs.add(p.Package__r.Name);
                    
                }
            }
        }
    }
    
    public static List<String> getDocsToSave(Id recordId) {
        system.debug(recordId);
        List<String> saveDocsList = new List<String>();
        List<String> alreadyAddDocs = new List<String>();
        Opportunity opport = [select id,
                              (select id, package__r.Name, 
                               package__r.DocumentTemplate__r.Id,
                               package__r.DocumentTemplate__r.Name,
                               package__r.DocumentTemplate__r.TemplateBodyHTML__c,
                               package__r.DocumentTemplate__r.isHTML__c
                               from Products__r) 
                              from opportunity 
                              where id =: recordId];

        List<AssociationDocumentTemplate__mdt> ladt = [select id, Template_to_use__c, Master_object__c, Vfp_used__c, order__c from AssociationDocumentTemplate__mdt order by order__c asc];

        for(AssociationDocumentTemplate__mdt adt : ladt) {
            for(Product__c p : opport.Products__r) {
                if(alreadyAddDocs.contains(p.Package__r.Name)) continue;
                String templateBody = p.package__r.DocumentTemplate__r.isHtml__c ? p.package__r.DocumentTemplate__r.TemplateBodyHTML__c : p.package__r.DocumentTemplate__r.TemplateBody__c;
                if(adt.Template_to_use__c == p.package__r.DocumentTemplate__r.Id) {
                    //saveDocsList.add('/apex/'+adt.Vfp_used__c+'?id='+recordId+'&masterObject='+adt.Master_object__c+'&relatedObject='+'Product__c'+'&relatedId='+p.Id+'&templateId='+adt.Template_to_use__c);
                    alreadyAddDocs.add(p.Package__r.Name);
                }
            }
        }
        saveDocsList.add('/apex/io_save?id='+recordId+'&masterObject=');
        return saveDocsList;
    }
}