force-app/main/default/objects/AssociationDocumentTemplate__mdt/AssociationDocumentTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Association des modeles de doc</label>
    <pluralLabel>Associations des modeles de doc</pluralLabel>
</CustomObject>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Master_object__c.field-meta.xml
<CustomField>
    <fullName>Master_object__c</fullName>
    <label>Master object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Template_to_use__c.field-meta.xml
<CustomField>
    <fullName>Template_to_use__c</fullName>
    <label>Id du template à utiliser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Vfp_used__c.field-meta.xml
<CustomField>
    <fullName>Vfp_used__c</fullName>
    <label>Vfp à utiliser</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentTemplate__c/DocumentTemplate__c.object-meta.xml
<CustomObject>
    <label>Modèle de document</label>
    <nameField>
        <label>Nom de DocumentTemplate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modèles de document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/AutoOppId__c.field-meta.xml
<CustomField>
    <fullName>AutoOppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Numéro d&apos;opportunité</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Numero_OI_BDC__c.field-meta.xml
<CustomField>
    <fullName>Numero_OI_BDC__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName =&apos;Promogaming&apos;,RecordType.DeveloperName =&apos;Promotion_Personnalisee&apos;,RecordType.DeveloperName =&apos;Autres&apos;) , &apos;BDC&apos;, &apos;OI&apos;) +
TRIM(right(AutoOppId__c, (LEN(AutoOppId__c) - 2)))</formula>
    <label>Numéro OI/BDC</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Catégorie</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Activation MD</fullName>
            </value>
            <value>
                <fullName>Activation Online</fullName>
            </value>
            <value>
                <fullName>Adex</fullName>
            </value>
            <value>
                <fullName>Etude et mesure</fullName>
            </value>
            <value>
                <fullName>Frais techniques</fullName>
            </value>
            <value>
                <fullName>Régule</fullName>
            </value>
            <value>
                <fullName>Display Onsite</fullName>
            </value>
            <value>
                <fullName>Forfait Visuels</fullName>
            </value>
            <value>
                <fullName>Promogaming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produits d&apos;opportunités</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/showData.cls
public with sharing class showData {
    //public static string cnval{get; set;}
    
    public class Link {
        String Name;
        String url;
    }
    /*@AuraEnabled public static string assignValue(string svr){cnval = svr;system.debug('aura-->'+cnval);return svr;}*/
    @AuraEnabled
    public static String getLinks(string recordId){
        List<link> listLinks = new List<link>();
        List<String> alreadyAddDocs = new List<String>();
        List<Integer> docsToRemove = new List<Integer>();
        Integer counter = 0;
        Map<id, AssociationDocumentTemplate__mdt> mapIdTemplate = new Map<id, AssociationDocumentTemplate__mdt>();
        Opportunity opport = [select id, AccountId, (select id, Category__c, package__r.Name, package__r.Category__c, package__r.DocumentTemplate__c , package__r.DocumentTemplate__r.Id from Products__r) 
                              from opportunity where id =: recordId];
        List<AssociationDocumentTemplate__mdt> ladt = [select id, MasterLabel, Template_to_use__c, Master_object__c, Vfp_used__c from AssociationDocumentTemplate__mdt];
        for(AssociationDocumentTemplate__mdt adt : ladt){
            if(adt.MasterLabel == 'Telemarketing' || adt.MasterLabel == 'Activation MD' ) docsToRemove.add(counter);
            counter++;
        }
        for(Integer docRef : docsToRemove) ladt.remove(docRef);
        for(AssociationDocumentTemplate__mdt adt : ladt) mapIdTemplate.put(adt.Template_to_use__c, adt);
        for(Product__c p : opport.Products__r) {
            system.debug(p.Package__r.DocumentTemplate__c);
            if(alreadyAddDocs.contains(p.Package__r.Id)) continue;
            system.debug(p.Package__r.DocumentTemplate__c + ' ' + mapIdTemplate.get(p.Package__r.DocumentTemplate__c));
            if(p.Package__r.DocumentTemplate__c != null && mapIdTemplate.get(p.Package__r.DocumentTemplate__c) != null){
                AssociationDocumentTemplate__mdt adt = mapIdTemplate.get(p.Package__r.DocumentTemplate__c);
                Link link = new Link();
                link.Name = adt.MasterLabel; link.url = '';
                if(adt.Master_object__c != null) link.url+= '&masterObject='+adt.Master_object__c;
                if(adt.Template_to_use__c != null) link.url+= '&templateId='+adt.Template_to_use__c;
                listLinks.add(link);
                alreadyAddDocs.add(p.Package__r.Id);
            }
        } 
        return JSON.serialize(listLinks);
    }
    
    @AuraEnabled
    public static void saveDocs(Id oppId){
        List<String> docsToSave = OIDocumentController.getDocsToSave(oppId);
        Opportunity opp = [select id, AutoOppId__c,Numero_OI_BDC__c from opportunity where id =: oppId];
        io_controller.save(oppId, opp.Numero_OI_BDC__c+'_', docsToSave[0] + oppId);
    }
    
    @AuraEnabled
    public static String fetchUrl(){
        string urler = URL.getSalesforceBaseUrl().toExternalForm();
        return (urler);
    }
}