force-app/main/default/objects/AssociationDocumentTemplate__mdt/AssociationDocumentTemplate__mdt.object-meta.xml
<CustomObject>
    <label>Association des modeles de doc</label>
    <pluralLabel>Associations des modeles de doc</pluralLabel>
</CustomObject>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Master_object__c.field-meta.xml
<CustomField>
    <fullName>Master_object__c</fullName>
    <label>Master object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/order__c.field-meta.xml
<CustomField>
    <fullName>order__c</fullName>
    <label>order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Template_to_use__c.field-meta.xml
<CustomField>
    <fullName>Template_to_use__c</fullName>
    <label>Id du template à utiliser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssociationDocumentTemplate__mdt/fields/Vfp_used__c.field-meta.xml
<CustomField>
    <fullName>Vfp_used__c</fullName>
    <label>Vfp à utiliser</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produits d&apos;opportunités</relationshipLabel>
    <relationshipName>OpportunityProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OISaveController.cls
public class OISaveController {
    
	public Opportunity opp{get;set;}
    public List<String> listDocs{get;set;}

    public OISaveController(ApexPages.StandardController stdController) {
        opp = (Opportunity)stdController.getRecord();
        listDocs = new List<String>();
        List<Document> saveDocsList = new List<Document>();
        List<String> alreadyAddDocs = new List<String>();
        Opportunity opport = [select id, 
                              (select id, package__r.Name, 
                               package__r.DocumentTemplate__r.Id,
                               package__r.DocumentTemplate__r.TemplateBodyHTML__c,
                               package__r.DocumentTemplate__r.isHTML__c from Products__r) 
                              from opportunity 
                              where id =: opp.Id];
        
        List<AssociationDocumentTemplate__mdt> ladt = [select id, MasterLabel, Template_to_use__c, Master_object__c, Vfp_used__c, order__c from AssociationDocumentTemplate__mdt order by order__c asc];
        
        for(AssociationDocumentTemplate__mdt adt : ladt) {
            for(Product__c p : opport.Products__r) {
                if(alreadyAddDocs.contains(p.Package__r.Name)) continue;
                String templateBody = p.package__r.DocumentTemplate__r.isHtml__c ? p.package__r.DocumentTemplate__r.TemplateBodyHTML__c : p.package__r.DocumentTemplate__r.TemplateBody__c;
                if(adt.Template_to_use__c == p.package__r.DocumentTemplate__r.Id && adt.MasterLabel == 'Telemarketing') {
                    PageReference page = new PageReference('/apex/io_save'+ '?id='+opp.Id+ '&masterObject='+adt.Master_object__c+ '&relatedObject='+'Product__c'+ '&relatedId='+p.Id);
                    listDocs.add(DocumentTemplateController.getDocumentBody(templateBody, page));
                    alreadyAddDocs.add(p.Package__r.Name);
                    
                }
            }
        }
    }
}