force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SentInvoice__c.field-meta.xml
<CustomField>
    <fullName>SentInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatiquement coché quand envoyé en facture</inlineHelpText>
    <label>Envoyé en facture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>validated</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Annulée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpenOrdersToFtp.cls
global class OpenOrdersToFtp implements Database.Batchable<sObject>, Schedulable{
    global OpenOrdersToFtp(){
    }
    
    global void execute(SchedulableContext SC) {
 		database.executebatch(new OpenOrdersToFtp()); 
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Name, Status__c, SentInvoice__c, Opportunity__r.RecordType.Name, Opportunity__r.CloseDate'
            +' FROM Invoice__c WHERE Status__c != \'validated\' AND Status__c != \'canceled\' AND SentInvoice__c != true'
            +' AND Opportunity__r.RecordType.name = \'Open Order\' AND CreatedDate = LAST_N_DAYS:3';
        //
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<Invoice__c> scope){
        system.debug(scope);
        List<Invoice__c> invList = new List<Invoice__c>();
        Set<Id> IdsToExport = new Set<Id>();
        List<Document> docList = new List<Document>();
        for(Invoice__c inv : scope){
            if(inv.SentInvoice__c != true){
                invList.add(inv);
                IdsToExport.add(inv.Id);
            }
        }
        Database.SaveResult[] srList = Database.update(invList, false);
        List<Invoice__c> exportInvList = gnx_export.queryInvoiceExportFields(IdsToExport);
        docList = new List<Document>(gnx_export.exportGnxSched(exportInvList));
        if(docList.size() > 0)System.enqueueJob(new QueueExportApi(docList, 'Regie3W_Export'));
    }    
    global void finish(Database.BatchableContext bc){
        
    } 
}