force-app/main/default/objects/Categorie_reservee__c/Categorie_reservee__c.object-meta.xml
<CustomObject>
    <label>Catégorie réservée</label>
    <nameField>
        <label>Catégorie réservée Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catégories réservées</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Categorie_reservee__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Catégorie active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Categorie_reservee__c/fields/Univers__c.field-meta.xml
<CustomField>
    <fullName>Univers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Univers</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Categorie_reservee__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Univers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Categorie_reservee__c</referenceTo>
    <relationshipLabel>Rayons</relationshipLabel>
    <relationshipName>Rayon</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Categorie_reservee__c/recordTypes/Rayon.recordType-meta.xml
<RecordType>
    <fullName>Rayon</fullName>
    <active>true</active>
    <label>Rayon</label>
</RecordType>

force-app/main/default/objects/Categorie_reservee__c/recordTypes/Univers.recordType-meta.xml
<RecordType>
    <fullName>Univers</fullName>
    <active>true</active>
    <label>Univers</label>
</RecordType>

force-app/main/default/classes/DynamicCategorieControllerTest.cls
@isTest class DynamicCategorieControllerTest {


    public static testmethod void test_getOpportunities() {

        Id recordTypeIDUnivers = Schema.SObjectType.Categorie_Reservee__c.getRecordTypeInfosByName().get('Univers').getRecordTypeId();
        Id recordTypeIDRayon = Schema.SObjectType.Categorie_Reservee__c.getRecordTypeInfosByName().get('Rayon').getRecordTypeId();


        /*DynamicCategorieController.parentwrapper pwtest = new DynamicCategorieController.parentwrapper(); 
        DynamicCategorieController.childwrapper cwtest = new DynamicCategorieController.childwrapper(); */
        
        Categorie_reservee__c categorietest = new Categorie_reservee__c();
        categorietest.Name = 'Test Categorie';
        categorietest.IsActive__c = true;
        categorietest.RecordTypeId=recordTypeIDUnivers;

        insert categorietest;

        System.debug('categorietest.RecordTypeId'+ categorietest.RecordTypeId);
        System.debug('categorietest.Id'+ categorietest.Id);

        Categorie_reservee__c categorietest1 = new Categorie_reservee__c();
        categorietest1.Name = 'Test Categorie1';
        categorietest1.IsActive__c = true;
        categorietest1.RecordTypeId=recordTypeIDRayon;
        categorietest1.Univers__c=categorietest.Id;

        insert categorietest1;


        System.debug('categorietest1.RecordTypeId'+ categorietest1.RecordTypeId);

        System.debug('categorietest1.Univers__c'+ categorietest1.Univers__c);



        DynamicCategorieController.getAllParentAccounts();
        DynamicCategorieController.getChildAccounts(categorietest.Id);
        DynamicCategorieController.getuniversedetails();



    }
}