force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Atterrissage</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atterrissages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BUs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Mois</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Janvier</fullName>
                <label>01-Janvier</label>
            </value>
            <value>
                <fullName>Février</fullName>
                <label>02-Février</label>
            </value>
            <value>
                <fullName>Mars</fullName>
                <label>03-Mars</label>
            </value>
            <value>
                <fullName>Avril</fullName>
                <label>04-Avril</label>
            </value>
            <value>
                <fullName>Mai</fullName>
                <label>05-Mai</label>
            </value>
            <value>
                <fullName>Juin</fullName>
                <label>06-Juin</label>
            </value>
            <value>
                <fullName>Juillet</fullName>
                <label>07-Juillet</label>
            </value>
            <value>
                <fullName>Août</fullName>
                <label>08-Août</label>
            </value>
            <value>
                <fullName>Septembre</fullName>
                <label>09-Septembre</label>
            </value>
            <value>
                <fullName>Octobre</fullName>
                <label>10-Octobre</label>
            </value>
            <value>
                <fullName>Novembre</fullName>
                <label>11-Novembre</label>
            </value>
            <value>
                <fullName>Décembre</fullName>
                <label>12-Décembre</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA signé ATT</label>
    <summarizedField>Forecast_Item__c.Revenue__c</summarizedField>
    <summaryFilterItems>
        <field>Forecast_Item__c.Signed_OI__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Forecast_Item__c.Forecast__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Année</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/Forecast_Item__c.object-meta.xml
<CustomObject>
    <label>Ligne d&apos;atterrissage</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Nom</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lignes d&apos;atterrissage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Item__c/fields/Block__c.field-meta.xml
<CustomField>
    <fullName>Block__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bloque la ligne d&apos;atterrissage</description>
    <label>Block</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <formula>text(Opportunity__r.BU__c)</formula>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Atterrissage</label>
    <referenceTo>Forecast__c</referenceTo>
    <relationshipLabel>Lignes d&apos;atterrissage</relationshipLabel>
    <relationshipName>Lignes_d_atterrissage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Produit d&apos;Opportunité</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Lignes d&apos;atterrissage</relationshipLabel>
    <relationshipName>Lignes_d_atterrissage</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast_Item__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA atterrissage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCAPTIF&quot;), &quot;Non Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBRP&quot;), &quot;Régie Physique&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBHORSCAPTIF&quot;), &quot;Hors Captif&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBALIMENTAIR&quot;), &quot;Alimentaire&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPART&quot;), &quot;Cashback Webloyalty&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBPROG&quot;), &quot;AdEx&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBNIP&quot;), &quot;NIP&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBAUTRES&quot;), &quot;Autres&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBCLAB&quot;), &quot;CLAB&quot;,
IF( ISPICKVAL(Opportunity__r.BU__c, &quot;ESPPUBW2S&quot;), &quot;WEB TO STORE&quot;,
&quot;&quot;

))))))))))</formula>
    <label>BU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>Utilisé en reporting</description>
    <formula>TEXT( Product__r.Medium__c )</formula>
    <label>Support</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ne pas mettre de filtres sur ce champ &gt; bug quand passage en OI signé</description>
    <label>Produit</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Produit d&apos;opération</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Utilisé pour le reporting</description>
    <formula>TEXT( Product__r.Type__c )</formula>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Produit d&apos;opportunité</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produits d&apos;opportunités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <label>Support</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3WRelevanc</fullName>
            </value>
            <value>
                <fullName>AppNexus</fullName>
            </value>
            <value>
                <fullName>Après l&apos;achat</fullName>
            </value>
            <value>
                <fullName>Banque Casino</fullName>
            </value>
            <value>
                <fullName>Base test</fullName>
            </value>
            <value>
                <fullName>Bonial</fullName>
            </value>
            <value>
                <fullName>Cap Pépita</fullName>
            </value>
            <value>
                <fullName>Caradisiac group</fullName>
            </value>
            <value>
                <fullName>CarData</fullName>
            </value>
            <value>
                <fullName>Carla Bikini</fullName>
            </value>
            <value>
                <fullName>Casino Drive</fullName>
            </value>
            <value>
                <fullName>Casino group</fullName>
            </value>
            <value>
                <fullName>Casino HM</fullName>
            </value>
            <value>
                <fullName>Casino SM</fullName>
            </value>
            <value>
                <fullName>Cdiscount</fullName>
            </value>
            <value>
                <fullName>Cdiscount Pro</fullName>
            </value>
            <value>
                <fullName>Cdiscount Voyages</fullName>
            </value>
            <value>
                <fullName>Chefclub</fullName>
            </value>
            <value>
                <fullName>Conforama</fullName>
            </value>
            <value>
                <fullName>DBM</fullName>
            </value>
            <value>
                <fullName>Email Retargeting</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Fidall</fullName>
            </value>
            <value>
                <fullName>Franprix</fullName>
            </value>
            <value>
                <fullName>Géant</fullName>
            </value>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Go Sport</fullName>
            </value>
            <value>
                <fullName>Kontiki Média</fullName>
            </value>
            <value>
                <fullName>Leader Price</fullName>
            </value>
            <value>
                <fullName>Lucky Cart</fullName>
            </value>
            <value>
                <fullName>Infinity Advertising</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>CA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3W Retail media plateform</fullName>
            </value>
            <value>
                <fullName>Adresses postales</fullName>
            </value>
            <value>
                <fullName>Affichage chariot</fullName>
            </value>
            <value>
                <fullName>Analyse de mixités</fullName>
            </value>
            <value>
                <fullName>Bannière HP Premium 1600x200</fullName>
            </value>
            <value>
                <fullName>bannières multiformats</fullName>
            </value>
            <value>
                <fullName>Bannières order process</fullName>
            </value>
            <value>
                <fullName>Cache antenne</fullName>
            </value>
            <value>
                <fullName>Cash Back</fullName>
            </value>
            <value>
                <fullName>Clab</fullName>
            </value>
            <value>
                <fullName>Concurrence win/lost sur Cdiscount</fullName>
            </value>
            <value>
                <fullName>Echantillons</fullName>
            </value>
            <value>
                <fullName>emailing BtoB</fullName>
            </value>
            <value>
                <fullName>emailing BtoC</fullName>
            </value>
            <value>
                <fullName>Etude Ad hoc</fullName>
            </value>
            <value>
                <fullName>Etude lancement de produit</fullName>
            </value>
            <value>
                <fullName>Etude produit à maturité/en déclin</fullName>
            </value>
            <value>
                <fullName>Frais technique</fullName>
            </value>
            <value>
                <fullName>Frais technique push SMS</fullName>
            </value>
            <value>
                <fullName>Google adsense</fullName>
            </value>
            <value>
                <fullName>Google adx</fullName>
            </value>
            <value>
                <fullName>Google shopping</fullName>
            </value>
            <value>
                <fullName>Habillage de page</fullName>
            </value>
            <value>
                <fullName>Interstitiel</fullName>
            </value>
            <value>
                <fullName>Kakémono</fullName>
            </value>
            <value>
                <fullName>Leaflets</fullName>
            </value>
            <value>
                <fullName>Lien partenaire</fullName>
            </value>
            <value>
                <fullName>Lien sponso Google</fullName>
            </value>
            <value>
                <fullName>Loc data - SMS</fullName>
            </value>
            <value>
                <fullName>Locdata - emailing BtoC</fullName>
            </value>
            <value>
                <fullName>Régule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ForecastHelperTest.cls
@isTest class ForecastHelperTest {
    static TestDataFactory t;
    static { t = new TestDataFactory(); }
    static testmethod void test_all() {
        User myUser = [SELECT Id FROM User LIMIT 1];
        ForecastHelper.getUserInfo(myUser.Id);
        Forecast__c forecast = new Forecast__c();
        forecast.BU__c = 'ESPPUBALIMENTAIR';
        forecast.Month__c = 'Août';
        forecast.Year__c = '2020';
        insert forecast;
        
        Forecast_Item__c fItem = new Forecast_Item__c();
        fItem.Block__c = true;
        fItem.Forecast__c = forecast.Id;
        fItem.Product__c = t.oppProductForecast.Id;
        fItem.Revenue__c = 15;
        insert fItem;
        
        Forecast_Item__c foreItem = new Forecast_Item__c();
        foreItem.Block__c = false;
        foreItem.Forecast__c = forecast.Id;
        foreItem.Product__c = t.oppProductForecast.Id;
        foreItem.Revenue__c = 30;
        insert foreItem;

        Product2 protest= new Product2();
        protest.Name='Testpro';
        protest.Type__c='Régule';
        protest.Medium__c='Infinity Advertising';
        insert protest;
        
        Insertion__c myIns = [SELECT Id, opportunity__r.Id FROM Insertion__c WHERE OpportunityProduct__c =: t.oppProductForecast.Id LIMIT 1];
        myIns.Status__c = 'Clôturé';
        myIns.Revenue__c = 50;
        myIns.OpportunityProduct__c = t.oppProductForecast.Id;
        update myIns;

        Set<Id> insertionsIds = new Set<Id>();
        insertionsIds.add(myIns.Id);
        List<Product__c> productsList = new List<Product__c>();
        productsList.add(t.oppProductForecast);
        Set<Id> insClosedToSigned = new Set<Id>();
        insClosedToSigned.add(myIns.Id);
        invoicing_controller.deleteInvoiceItems(insClosedToSigned);
        ForecastHelper.handleReOpeningInsertion(insertionsIds);
        ForecastHelper.addInsertions(productsList);
    }
}