force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BillingEntity__c/fields/InvoicePrefix__c.field-meta.xml
<CustomField>
    <fullName>InvoicePrefix__c</fullName>
    <label>Invoice prefix</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BillingEntity__c/fields/LastInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>LastInvoiceNumber__c</fullName>
    <label>Last invoice number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insertion__c/Insertion__c.object-meta.xml
<CustomObject>
    <label>Insertion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insertions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insertion__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Insertions</relationshipLabel>
    <relationshipName>Insertions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insertion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OI facturé</fullName>
            </value>
            <value>
                <fullName>Clôturé</fullName>
            </value>
            <value>
                <fullName>Signé</fullName>
            </value>
            <value>
                <fullName>Signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI signé/contrôlé</fullName>
            </value>
            <value>
                <fullName>OI clôturé</fullName>
            </value>
            <value>
                <fullName>OI signé</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <formula>Opportunity__r.BillingEntity__r.Name</formula>
    <label>Entité de facturation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Date Facture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <externalId>true</externalId>
    <label>N° Facture</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceTerm__c.field-meta.xml
<CustomField>
    <fullName>InvoiceTerm__c</fullName>
    <label>Date d&apos;échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Factures</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OriginalInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>OriginalInvoiceNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Facture annulée d&apos;où provient l&apos;avoir</inlineHelpText>
    <label>Facture d&apos;origine</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Avoirs</relationshipLabel>
    <relationshipName>Factures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ProvisionSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisionSent__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatiquement coché quand envoyé en provision</inlineHelpText>
    <label>Envoyé en provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SentInvoice__c.field-meta.xml
<CustomField>
    <fullName>SentInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatiquement coché quand envoyé en facture</inlineHelpText>
    <label>Envoyé en facture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>validated</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Annulée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <label>Ligne de facture</label>
    <nameField>
        <label>Nom de la ligne de facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lignes de facture</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/Insertion__c.field-meta.xml
<CustomField>
    <fullName>Insertion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insertion</label>
    <referenceTo>Insertion__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>InvoiceItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Facture</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Lignes de facture</relationshipLabel>
    <relationshipName>invoiceitems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceNumber__c/InvoiceNumber__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>InvoiceNumber</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité de facturation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>BillingEntity__c.Name</field>
            <operation>notContain</operation>
            <value>Maxit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BillingEntity__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InsertionOrderId__c.field-meta.xml
<CustomField>
    <fullName>InsertionOrderId__c</fullName>
    <displayFormat>OI{000000}</displayFormat>
    <label>Numéro d&apos;OI</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/invoicing_validator.cls
global class invoicing_validator {
    public class validatorException extends Exception {}
    
    global class validatorRequest {
        @InvocableVariable(label='Facture' required=true)
        public ID invoiceId;
        
        @InvocableVariable(label='Entité de facturation' required=true)
        public ID billingEntity;
    }
    
    @InvocableMethod(label='Valide la facture')
    global static void send(List<validatorRequest> requests) {
        for(Integer i=0;i<requests.size();i++){
            if(requests[i].BillingEntity == null) throw new validatorException('Erreur : La requête '+requests[i].invoiceId+' n\'a pas d\'Entité de facturation');
        }
        Date invoiceDate = Date.today();
        Date invoiceTermDate = invoiceDate.addDays(30);
        List<Invoice__c> invoices = new List<Invoice__c>();
        Set<Id> invoiceIds = new Set<Id>();
        
        Set<id> oldInvoicesids = new Set<Id>();
        Map<Id, Invoice__c> avoirSelector = new Map<Id, Invoice__c>();
        for(Integer i=0;i<requests.size();i++){
            oldInvoicesids.add(requests[i].invoiceId);
        }
        List<Invoice__c> oldInvoices = [SELECT Id, OriginalInvoiceNumber__c, Status__c, Opportunity__r.InsertionOrderId__c FROM Invoice__c WHERE Id IN :oldInvoicesids];
        for(Invoice__c i : oldInvoices){
            avoirSelector.put(i.Id, i);
        }
        
        Map<Id, BillingEntity__c> BillingEntityMap = new Map<Id, BillingEntity__c>([SELECT Id, LastInvoiceNumber__c, InvoicePrefix__c FROM BillingEntity__c FOR UPDATE]);
        for (validatorRequest r : requests) {
            system.debug(r.billingEntity + ' - ' + BillingEntityMap.get(r.billingEntity));
            BillingEntityMap.get(r.billingEntity).LastInvoiceNumber__c = BillingEntityMap.get(r.billingEntity).LastInvoiceNumber__c + 1; 
            invoiceIds.add(r.invoiceId);

            Invoice__c newInvoice = new Invoice__c(
                Id = r.invoiceId,
                InvoiceDate__c = invoiceDate,
                InvoiceTerm__c = invoiceTermDate
            );

            if(String.isBlank(avoirSelector.get(r.invoiceId).OriginalInvoiceNumber__c) == true){
                newInvoice.Name = BillingEntityMap.get(r.billingEntity).InvoicePrefix__c + String.valueOf(Date.today().year()).substring(2) + String.valueOf(BillingEntityMap.get(r.billingEntity).LastInvoiceNumber__c).leftPad(4,'0');
                newInvoice.InvoiceNumber__c = BillingEntityMap.get(r.billingEntity).InvoicePrefix__c + String.valueOf(Date.today().year()).substring(2) + String.valueOf(BillingEntityMap.get(r.billingEntity).LastInvoiceNumber__c).leftPad(4,'0');
                invoices.add(newInvoice);
            }else{
                if(avoirSelector.get(r.invoiceId).Status__c == 'validated'){
                    newInvoice.Name = BillingEntityMap.get(r.billingEntity).InvoicePrefix__c + String.valueOf(Date.today().year()).substring(2) + String.valueOf(BillingEntityMap.get(r.billingEntity).LastInvoiceNumber__c).leftPad(4,'0') + ' - Avoir';
                    newInvoice.InvoiceNumber__c = BillingEntityMap.get(r.billingEntity).InvoicePrefix__c + String.valueOf(Date.today().year()).substring(2) + String.valueOf(BillingEntityMap.get(r.billingEntity).LastInvoiceNumber__c).leftPad(4,'0');
                    invoices.add(newInvoice);
                }else{
                    newInvoice.Name = 'PROFORMA - '+ avoirSelector.get(r.invoiceId).Opportunity__r.InsertionOrderId__c + ' - Avoir';
                    newInvoice.SentInvoice__c = false;
                    newInvoice.ProvisionSent__c = false;
                    invoices.add(newInvoice);
                }
            }
        }
        update invoices;
        
        List<insertion__c> insertions = new List<insertion__c>();
        for(InvoiceItem__c i : [select insertion__c from InvoiceItem__c where invoice__c in :invoiceIds and insertion__c != null ]) insertions.add(new Insertion__c(Id = i.insertion__c, status__c = 'OI facturé'));
        
        update insertions;
        update BillingEntityMap.values();
    }
}