force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agence</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunités (Agence)</relationshipLabel>
    <relationshipName>AgencyOpportunies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AutoOppId__c.field-meta.xml
<CustomField>
    <fullName>AutoOppId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Numéro d&apos;opportunité</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entité de facturation</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>BillingEntity__c.Name</field>
            <operation>notContain</operation>
            <value>Maxit</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BillingEntity__c</referenceTo>
    <relationshipLabel>Opportunités</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CampaignStartDate__c.field-meta.xml
<CustomField>
    <fullName>CampaignStartDate__c</fullName>
    <label>Date de début théorique</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InsertionOrderId__c.field-meta.xml
<CustomField>
    <fullName>InsertionOrderId__c</fullName>
    <displayFormat>OI{000000}</displayFormat>
    <label>Numéro d&apos;OI</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InvoicedAccount__c.field-meta.xml
<CustomField>
    <fullName>InvoicedAccount__c</fullName>
    <label>Payeur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annonceur</fullName>
                <default>true</default>
                <label>Annonceur</label>
            </value>
            <value>
                <fullName>Agence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InvoicingLevel__c.field-meta.xml
<CustomField>
    <fullName>InvoicingLevel__c</fullName>
    <label>Niveau de facturation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contrat</fullName>
                <default>true</default>
                <label>Open Order (Contrat)</label>
            </value>
            <value>
                <fullName>Campagne</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TechnicalFeesInvoicing__c.field-meta.xml
<CustomField>
    <fullName>TechnicalFeesInvoicing__c</fullName>
    <label>Facturation des frais techniques</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agence/Annonceur</fullName>
            </value>
            <value>
                <fullName>Agence</fullName>
                <default>true</default>
                <label>Agence</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler extends TriggerHandler {
    Map<Id, Opportunity> newMap;
    Map<Id, Opportunity> oldMap;
    List<Opportunity> newList;
    List<Opportunity> oldList;
    Boolean sizeForSchedule;

    public class OpportunityTriggerHandlerException extends Exception {}
 
    public OpportunityTriggerHandler() {
       super('OpportunityTriggerHandler');
       oldMap = (Map<Id, Opportunity>) Trigger.oldMap;
       newMap = (Map<Id, Opportunity>) Trigger.newMap;
       oldList = Trigger.old;
       newList = Trigger.new;
       sizeForSchedule = newList != null ? newList.size() >= 100 : false;
    }
 
    public override void afterInsert() {
        List<Opportunity> oppList = [SELECT Id, Owner.BU__c, RecordTypeId, RecordType.Name, BU__c, InsertionOrderId__c, CampaignStartDate__c, OwnerId FROM Opportunity WHERE Id IN: newMap.keySet()];
        List<BillingEntity__c> billingEntList = [SELECT Id, Name FROM BillingEntity__c WHERE Name = 'Infinity Advertising' LIMIT 1];
        system.debug('billingEntList.size()'+billingEntList.size());
        system.debug('billingEntList'+billingEntList);

        Id billingEntityId;
        if(billingEntList.size() > 0){
            billingEntityId = billingEntList[0].Id;
        }else{
            throw new OpportunityTriggerHandlerException('L\'entité de facturation "Infinity Advertising" est introuvable');
        }
        for(Opportunity opp : oppList){
//            opp.BU__c = opp.Owner.BU__c;
            opp.BillingEntity__c = billingEntityId;
            opp.AutoOppId__c = opp.InsertionOrderId__c;
        }
        update oppList;
    }

    
    public override void afterUpdate() {
        if(Recursion.oppRecursion) return;
        Recursion.oppRecursion = true;
        
        Set<id> opps = new Set<id>();
        Set<id> invoicingLevelOpps = new Set<id>();
        Set<id> technicalFeesInvoicingOpps = new Set<id>();
        Set<id> invoicingStageNameOpps = new Set<id>();
        
        // create insertions
        invoicing_controller.createInsertions(newMap.keySet());
        
        for(Opportunity opp : newList) {
            Opportunity oldOpp = oldMap.get(opp.id);
            
            //if account/agency/BU/Invoiced account changed
            if(opp.AccountId != oldOpp.AccountId  || opp.Agency__c != oldOpp.Agency__c  || opp.BU__c != oldOpp.BU__c || opp.InvoicedAccount__c != oldOpp.InvoicedAccount__c) opps.add(opp.Id);
            
            //if InvoicingLevel__c changed
            if(opp.InvoicingLevel__c != oldOpp.InvoicingLevel__c) invoicingLevelOpps.add(opp.id);
            
            //if TechnicalFeesInvoicing__c changed
            if(opp.TechnicalFeesInvoicing__c != oldOpp.TechnicalFeesInvoicing__c) technicalFeesInvoicingOpps.add(opp.id);
            
            //if StageName changed
            if(opp.StageName != oldOpp.StageName) invoicingStageNameOpps.add(opp.id);
        }
        
        if(opps.size() > 0) 						invoicing_controller.updateProforma(opps);
        if(invoicingLevelOpps.size() > 0) 			invoicing_controller.handleInvoicingLevel(invoicingLevelOpps);
        if(technicalFeesInvoicingOpps.size() > 0) 	invoicing_controller.handleTechnicalFeesInvoicing(technicalFeesInvoicingOpps);
        if(invoicingStageNameOpps.size() > 0) 		ForecastHelper.handleOppStageName(invoicingStageNameOpps);
        
        Recursion.oppRecursion = false;
    }  


}