force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <formula>Opportunity__r.BillingEntity__r.Name</formula>
    <label>Entité de facturation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SentInvoice__c.field-meta.xml
<CustomField>
    <fullName>SentInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatiquement coché quand envoyé en facture</inlineHelpText>
    <label>Envoyé en facture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>validated</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Annulée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/invoice_export_batch.cls
global class invoice_export_batch implements Database.Batchable<sObject>, Schedulable{
    global String query = 'SELECT Id, Name, Status__c, SentInvoice__c, BillingEntity__c FROM Invoice__c WHERE Status__c = \'validated\' AND SentInvoice__c != true';
    
    global invoice_export_batch(){
        if(Database.query(query).isEmpty()){ //Si rien a exporter, envoyer un fichier vide
            List<Document> documents = new List<Document>{new Document(
                body = Blob.valueOf('  '),
                folderid = UserInfo.getUserId(),
                name = 'winLogic_InfinityAds_empty.tgt'
            )};
            System.enqueueJob(new invoice_export_queue(documents));
        }
    }
    
    global void execute(SchedulableContext SC) {
 		database.executebatch(new invoice_export_batch()); 
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query); 
    }
    global void execute(Database.BatchableContext bc, List<Invoice__c> scope){
        try{
            Set<Id> IdsToExport = new Set<Id>();
            for(Invoice__c inv : scope){
                IdsToExport.add(inv.Id);
            } 
            List<Invoice__c> exportInvList = invoice_export.queryInvoiceExportFields(IdsToExport);
            List<Document> documents = new List<Document>{invoice_export.exportInfinitySched(exportInvList)};
            System.enqueueJob(new invoice_export_queue(documents));
        }catch(Exception e){
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.toAddresses = new String[]{'Projet@isochronix.com'};mail.setSubject('API Infinity Ads : Erreur lors de l\'export en masse');mail.setPlainTextBody('Message : '+e.getMessage()+' line : '+e.getLineNumber());
        	Messaging.SendEmailResult[] results = Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{mail});
        }
    }    
    global void finish(Database.BatchableContext bc){
        
    } 
}