force-app/main/default/objects/BillingEntity__c/BillingEntity__c.object-meta.xml
<CustomObject>
    <label>Entité de facturation</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entités de facturation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Facture</label>
    <nameField>
        <label>Nom de la facture</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Factures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Avoir__c.field-meta.xml
<CustomField>
    <fullName>Avoir__c</fullName>
    <formula>NOT(ISBLANK( OriginalInvoiceNumber__c ))</formula>
    <label>Avoir ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/BillingEntity__c.field-meta.xml
<CustomField>
    <fullName>BillingEntity__c</fullName>
    <formula>Opportunity__r.BillingEntity__r.Name</formula>
    <label>Entité de facturation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SentInvoice__c.field-meta.xml
<CustomField>
    <fullName>SentInvoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatiquement coché quand envoyé en facture</inlineHelpText>
    <label>Envoyé en facture</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <default>true</default>
                <label>Brouillon</label>
            </value>
            <value>
                <fullName>validated</fullName>
                <label>Validée</label>
            </value>
            <value>
                <fullName>canceled</fullName>
                <label>Annulée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalExcludingVat__c.field-meta.xml
<CustomField>
    <fullName>TotalExcludingVat__c</fullName>
    <label>Total HT</label>
    <summarizedField>InvoiceItem__c.TotalExcludingVat__c</summarizedField>
    <summaryForeignKey>InvoiceItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/AaeBatchExport.cls
global class AaeBatchExport implements Database.Batchable<sObject>, Schedulable, Database.Stateful{
    global Integer invCounter = 0;
    global List<String> exceptionList = new List<String>();
    
    global AaeBatchExport(){}
    
    global void execute(SchedulableContext SC) {
        BusinessHours bh = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
        Datetime targetTime = Datetime.now();
        Datetime nextStart = BusinessHours.nextStartDate(bh.id, targetTime);
        String cronVar = '0 0 21 '+nextStart.day()+' '+nextStart.month()+' ? '+nextStart.year();
        
        if(BusinessHours.isWithin(bh.id, targetTime)) database.executebatch(this, 200);
        else System.schedule('nextAaeBatchExport', cronVar, this);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(Test.isRunningTest()){
            return Database.getQueryLocator('SELECT Id, Name, Status__c, SentInvoice__c, BillingEntity__c FROM Invoice__c WHERE Status__c = \'draft\'');
        } else {
            return Database.getQueryLocator('SELECT Id, Name, Status__c, SentInvoice__c, BillingEntity__c FROM Invoice__c WHERE Avoir__c = true AND BillingEntity__c = \'Relevanc\' AND Status__c = \'draft\' AND TotalExcludingVat__c < 0 AND CreatedDate >= 2021-02-01T00:00:00Z'); 
        }
    }
    
    global void execute(Database.BatchableContext bc, List<Invoice__c> scope){
        try{
            List<Invoice__c> exportInvList = gnx_export.queryInvoiceExportFields(new Map<Id, Invoice__c>(scope).keySet());
            invCounter += exportInvList.size();
            List<Document> docList = new List<Document>{faeaae_export.exportAaeSched(exportInvList)};
                System.enqueueJob(new QueueExportApi(docList, 'Regie3W_Export'));
            if(Test.isRunningTest()) throw new aaeException('test');
        }catch(Exception e){
            exceptionList.add('Message : '+e.getMessage()+' line : '+e.getLineNumber());
        }
    }   
    
    global void finish(Database.BatchableContext bc){
        if(invCounter == 0) System.enqueueJob(new QueueExportApi(new List<Document>{new Document(body = Blob.valueOf('  '),folderid = UserInfo.getUserId(),name = 'SA1RLVAP_'+System.now().format('yyyyMMddHHmmssSSS')+'.tgt')}, 'Regie3W_Export'));
        if(exceptionList.size() != 0){
            List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
            for(String msg : exceptionList){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.toAddresses = new String[]{'Projet@isochronix.com'};
                mail.setSubject('API 3wRegie/RelevanC : Erreur lors de l\'export en masse');
                mail.setPlainTextBody(msg);
                mailList.add(mail);
            }
            Messaging.SendEmailResult[] results = Messaging.sendEmail(mailList);
        }
    }
    
    public class aaeException extends Exception {}
}